Repository dart-lang/site-www, pull requests merged in 2018-06, with the labels that each got.

#902 Update example to comply with = for default parameters.
  examples/misc/lib/effective_dart/design_good.dart
  src/_guides/language/effective-dart/design.md
Labels: cla: yes

#904 Update typedef to use new Dart 2 syntax.
  examples/misc/lib/effective_dart/style_good.dart
  src/_guides/language/effective-dart/style.md
Labels: cla: yes

#905 Re-enable homepage "Open in DartPad" button
  src/index.html
Labels: cla: yes

#906 Fix countActivePlayers example
  examples/misc/lib/effective_dart/usage_bad.dart
  examples/misc/lib/effective_dart/usage_good.dart
  src/_guides/language/effective-dart/usage.md
Labels: cla: yes

#908 Adjust tests for full Dart 2 runtime semantics; upgrade to SDK 2-dev.60 and enable --preview-dart-2 for example tests
  .travis.yml
  examples/analysis_options.yaml
  examples/misc/analyzer-2-results.txt
  examples/misc/lib/language_tour/generics/base_class.dart
  examples/misc/lib/language_tour/generics/misc.dart
  examples/misc/test/effective_dart_test.dart
  examples/misc/test/language_tour/classes_test.dart
  examples/misc/test/language_tour/exceptions_test.dart
  examples/misc/test/language_tour/generics_test.dart
  scripts/analyze-and-test-examples.sh
  scripts/refresh-code-excerpts.sh
  src/_data/pkg-vers.json
  src/_guides/language/effective-dart/usage.md
  src/_guides/language/language-tour.md
Labels: Examples, cla: yes

#892 update google privacy policy url
  src/_includes/page-footer.html
Labels: cla: yes

#910 Remove 'new' from the homepage sample
  examples/misc/lib/pi_monte_carlo.dart
  src/_main-example.html
  src/index.html
Labels: cla: yes

#912 chore: use new code excerpter
  build.excerpt.yaml
  examples/misc/lib/effective_dart/design_good.dart
  examples/misc/lib/effective_dart/docs_bad.dart
  examples/misc/lib/effective_dart/docs_good.dart
  examples/misc/lib/effective_dart/style_lib_good.dart
  examples/misc/lib/language_tour/built_in_types.dart
  examples/misc/lib/language_tour/classes/employee.dart
  examples/misc/lib/language_tour/classes/impostor.dart
  examples/misc/lib/language_tour/classes/misc.dart
  examples/misc/lib/language_tour/classes/point.dart
  examples/misc/lib/language_tour/classes/point_alt.dart
  examples/misc/lib/language_tour/classes/point_with_main.dart
  examples/misc/lib/language_tour/control_flow.dart
  examples/misc/lib/language_tour/exceptions.dart
  examples/misc/lib/language_tour/functions.dart
  examples/misc/lib/language_tour/metadata/television.dart
  examples/misc/lib/language_tour/operators.dart
  examples/misc/lib/library_tour/core/iterator.dart
  examples/misc/lib/library_tour/io/http_server.dart
  examples/misc/lib/tutorial/daily_news.dart
  examples/misc/test/effective_dart_test.dart
  examples/misc/test/language_tour/classes_test.dart
  examples/misc/test/language_tour/generics_test.dart
  examples/misc/test/language_tour/operators_test.dart
  examples/misc/test/library_tour/core_test.dart
  examples/misc/test/library_tour/io_test.dart
  examples/strong/analyzer-2-results.txt
  examples/strong/lib/animal.dart
  examples/strong/test/strong_test.dart
  package.json
  pubspec.yaml
  scripts/install.sh
  scripts/refresh-code-excerpts.sh
  src/_guides/language/effective-dart/design.md
  src/_guides/language/effective-dart/style.md
  src/_guides/language/language-tour.md
  src/_guides/language/sound-problems.md
  src/_guides/libraries/library-tour.md
  src/_tutorials/language/futures.md
  src/dart-vm/io-library-tour.md
Labels: Infrastructure, cla: yes

#915 Add api.dartlang.org link to every page
  src/_includes/page-footer.html
Labels: cla: yes

#911 Recommend filenames for package examples
  src/tools/pub/package-layout.md
Labels: cla: yes

#917 Tweak example name discussion
  src/tools/pub/package-layout.md
Labels: cla: yes

#919 chore: upgrade to SDK 2-dev.61, rename deprecated constants
  .travis.yml
  examples/httpserver/bin/basic_writer_client.dart
  examples/httpserver/bin/basic_writer_server.dart
  examples/httpserver/bin/mini_file_server.dart
  examples/httpserver/bin/note_server.dart
  examples/httpserver/bin/number_guesser.dart
  examples/httpserver/bin/number_thinker.dart
  examples/misc/lib/library_tour/io/http_server.dart
  scripts/analyze-and-test-examples.sh
  src/_data/pkg-vers.json
  src/_tutorials/dart-vm/httpserver.md
  src/dart-vm/io-library-tour.md
Labels: cla: yes

#918 Fix typedef examples.
  examples/misc/lib/effective_dart/design_good.dart
  src/_guides/language/effective-dart/design.md
Labels: cla: yes

#922 HTTP tutorial: remove "not Dart-2" warning since it was updated a while ago
  src/_tutorials/dart-vm/httpserver.md
Labels: cla: yes

#924 Upgrade to SDK 2-dev.62
  .travis.yml
  pubspec.yaml
  scripts/before-install.sh
  scripts/refresh-code-excerpts.sh
  src/_data/pkg-vers.json
Labels: cla: yes

#923 Use new typedef syntax everywhere
  examples/misc/lib/language_tour/typedefs/misc.dart
  examples/misc/lib/language_tour/typedefs/sorted_collection_2.dart
  examples/strong/analyzer-2-results.txt
  examples/strong/lib/common_fixes_analysis.dart
  examples/strong/lib/common_problems_analysis.dart
  src/_guides/language/language-tour.md
  src/_guides/language/sound-problems.md
Labels: Docs, cla: yes

#931 Language tour: drop note about "new" typedef syntax
  src/_guides/language/language-tour.md
Labels: LanguageTour, cla: yes

#934 chore: sitemap fix, and Jekyll layout alias cleanup
  _config.yml
  src/_articles/dart-vm/benchmarking.md
  src/_articles/dart-vm/io.md
  src/_articles/dart-vm/native-extensions.md
  src/_articles/dart-vm/numeric-computation.md
  src/_articles/dart-vm/reflection-with-mirrors.md
  src/_articles/dart-vm/simd.md
  src/_articles/language/await-async.md
  src/_articles/language/beyond-async.md
  src/_articles/language/emulating-functions.md
  src/_articles/language/mixins.md
  src/_articles/libraries/broadcast-streams.md
  src/_articles/libraries/creating-streams.md
  src/_articles/libraries/serialization.md
  src/_codelabs/images/flutter-firebase.png
  src/_codelabs/images/flutter.png
  src/_guides/get-started.md
  src/_guides/language/analysis-options.md
  src/_guides/language/effective-dart/design.md
  src/_guides/language/effective-dart/documentation.md
  src/_guides/language/effective-dart/index.md
  src/_guides/language/effective-dart/usage.md
  src/_guides/libraries/library-tour.md
  src/_layouts/article.html
  src/_layouts/codelab.html
  src/_layouts/guide.html
  src/_layouts/sample.html
  src/codelabs/index.md
  src/samples/index.md
  src/sitemap.xml
Labels: Infrastructure, cla: yes

#935 Upgrade to SDK 2-dev.63
  .travis.yml
  src/_data/pkg-vers.json
Labels: cla: yes

#936 Update DartPad screenshot
  src/_assets/images/dartpad-hello.png
Labels: cla: yes

#937 chore: adjust dependency to linkcheck; other misc fixes
  pubspec.yaml
  src/tools/analyzer.md
  src/tools/dartpad.md
Labels: cla: yes

#939 chore: switch to pub hosted linkcheck
  pubspec.yaml
Labels: Infrastructure, cla: yes

#942 Fix lint name unnecessary_brace_in_string_interps
  src/_guides/language/analysis-options.md
Labels: cla: yes

#938 Add instantiate-to-bound example to "Fixing common type problems"
  examples/strong/analyzer-2-results.txt
  examples/strong/lib/bounded/instantiate_to_bound.dart
  examples/strong/lib/bounded/my_collection.dart
  examples/strong/test/strong_test.dart
  src/_guides/language/sound-problems.md
Labels: Dart2, Docs, cla: yes

#951 Upgrade to SDK 2-dev.64.1
  .travis.yml
  examples/README.md
  examples/httpserver/pubspec.yaml
  examples/misc/pubspec.yaml
  examples/strong/pubspec.yaml
  examples/util/pubspec.yaml
  scripts/analyze-and-test-examples.sh
  src/_data/pkg-vers.json
Labels: cla: yes

#945 Add new and const to /dart-2
  src/dart-2.md
Labels: cla: yes

#956 chore: bound build_runner version
  pubspec.yaml
Labels: Infrastructure, cla: yes

#944 Create /guides/json
  src/_guides/json.md
Labels: cla: yes

#957 chore: reinstate link checking
  .travis.yml
  pubspec.yaml
  scripts/refresh-code-excerpts.sh
Labels: Infrastructure, cla: yes

#955 Add warning about VM deferred libraries
  src/_guides/language/language-tour.md
Labels: cla: yes

#948 Update "Effective Dart" for optional new/const.
  examples/misc/lib/effective_dart/design_bad.dart
  examples/misc/lib/effective_dart/design_good.dart
  examples/misc/lib/effective_dart/style_bad.dart
  examples/misc/lib/effective_dart/style_good.dart
  examples/misc/lib/effective_dart/usage_bad.dart
  examples/misc/lib/effective_dart/usage_good.dart
  src/_guides/language/effective-dart/design.md
  src/_guides/language/effective-dart/style.md
  src/_guides/language/effective-dart/toc.md
  src/_guides/language/effective-dart/usage.md
Labels: cla: yes

#959 Remove unnecessary `new` from text
  src/_guides/language/language-tour.md
Labels: cla: yes

#963 Upgrade SDK to 2-dev.65
  .travis.yml
  examples/misc/lib/language_tour/built_in_types.dart
  examples/misc/lib/tutorial/misc.dart
  scripts/dartfmt.sh
  src/_data/pkg-vers.json
  src/_guides/language/language-tour.md
  src/_tutorials/language/futures.md
Labels: cla: yes

#961 Update platforms.md
  src/_guides/platforms.md
Labels: cla: yes

#964 Install page: Dart VM -> Server
  src/install.md
Labels: cla: yes

#970 Remove "Dart VM" from sidenav
  src/_articles/dart-vm/index.md
  src/_data/side-nav.yml
  src/_includes/article_index_warning.md
  src/_includes/page-footer.html
  src/dart-vm/index.md
Labels: cla: yes

#966 run dartfmt --fix on examples
  examples/httpserver/bin/basic_file_server.dart
  examples/httpserver/bin/basic_writer_client.dart
  examples/httpserver/bin/basic_writer_server.dart
  examples/httpserver/bin/hello_world_server_secure.dart
  examples/httpserver/bin/mini_file_server.dart
  examples/httpserver/bin/note_server.dart
  examples/httpserver/bin/number_guesser.dart
  examples/httpserver/bin/number_thinker.dart
  examples/httpserver/bin/static_file_server.dart
  examples/httpserver/test/httpserver_test.dart
  examples/httpserver/web/note_client.dart
  examples/misc/lib/language_tour/built_in_types.dart
  examples/misc/lib/language_tour/variables.dart
  examples/misc/lib/library_tour/async/stream.dart
  examples/misc/lib/library_tour/core/hash_code.dart
  examples/misc/lib/library_tour/core/iterator.dart
  examples/misc/lib/library_tour/io/http_server.dart
  examples/misc/lib/samples/spacecraft.dart
  examples/misc/lib/tutorial/cat_no_hash.dart
  examples/misc/lib/tutorial/daily_news.dart
  examples/misc/lib/tutorial/sum_stream_with_catch.dart
  examples/misc/test/effective_dart_test.dart
  examples/misc/test/library_tour/core_test.dart
  examples/misc/test/library_tour/io_test.dart
  examples/misc/test/library_tour/math_test.dart
  examples/misc/test/samples_test.dart
  examples/strong/lib/animal_bad.dart
  examples/strong/lib/bounded/instantiate_to_bound.dart
  examples/strong/lib/common_problems_analysis.dart
  examples/strong/lib/dart_1_my_list_hello_world.dart
  examples/strong/lib/strong_analysis.dart
  examples/strong/test/strong_test.dart
  examples/util/lib/dart_version.dart
  examples/util/lib/logger.dart
  src/_assets/stylesheets/main.scss
  src/_guides/language/effective-dart/usage.md
  src/_guides/language/language-tour.md
  src/_guides/language/sound-dart.md
  src/_guides/language/sound-problems.md
  src/_guides/libraries/library-tour.md
  src/_tutorials/dart-vm/httpserver.md
  src/_tutorials/language/futures.md
  src/_tutorials/language/streams.md
  src/dart-vm/io-library-tour.md
  src/samples/index.md
Labels: Dart2, Docs, Examples, cla: yes

#973 Ensure that non-Dart-2 pages are marked as such
  examples/misc/lib/tutorial/daily_news.dart
  examples/strong/analyzer-2-results.txt
  examples/strong/lib/strong_analysis.dart
  src/_guides/get-started.md
  src/_guides/language/effective-dart/documentation.md
  src/_guides/language/images/consumer-producer-assignment.png
  src/_guides/language/sound-dart.md
  src/_guides/libraries/futures-error-handling.md
  src/_includes/page-header.html
  src/_tutorials/language/futures.md
Labels: cla: yes

#979 Upgrade to SDK 2-dev.66
  .travis.yml
  src/_data/pkg-vers.json
Labels: cla: yes
