Repository dart-lang/site-www, pull requests merged in 2018-03, with the labels that each got.

#619 Move VS Code above the supported line
  src/tools/index.md
Labels: cla: yes

#621 Code excerpt checking for Dart 2 page
  examples/strong/analyzer-1-results.txt
  examples/strong/analyzer-2-results.txt
  examples/strong/lib/strong_analysis.dart
  src/_plugins/prettify.rb
  src/dart-2.md
Labels: Examples, SoundDart, cla: yes

#615 Add info about .dart_tool and .pub directories
  src/_guides/libraries/private-files.md
Labels: cla: yes

#623 Fixes typo: `substract` => `subtract`.
  src/_guides/language/sound-dart.md
Labels: cla: yes

#626 chore: env-set.sh and README updates
  .travis.yml
  README.md
  scripts/env-set.sh
Labels: Infrastructure, cla: yes

#627 Add space between rows in IDE list
  src/_assets/stylesheets/main.scss
  src/tools/index.md
Labels: cla: yes

#625 Remove toc from tutorials main page
  src/_guides/index.md
  src/_tutorials/index.md
Labels: Design, Docs, cla: yes

#631 Fixe misformatting of <pre> elements generated by prettifier
  src/_plugins/prettify.rb
Labels: Infrastructure, cla: yes

#633 chore: config tweaks before creating 1.x
  .travis.yml
  src/tools/sdk.md
Labels: Infrastructure, cla: yes

#635 chore: start using master for Dart 2
  .github/PULL_REQUEST_TEMPLATE.md
  .travis.yml
  _config.yml
Labels: Infrastructure, cla: yes

#636 chore: ensure site build shown in footer info is complete
  scripts/write-ci-info.sh
Labels: Infrastructure, cla: yes

#638 chore: sync deploy script with webdev
  deploy/deploy-firebase.sh
Labels: Infrastructure, cla: yes

#639 Tweaks to pubspec example
  src/tools/pub/pubspec.md
Labels: cla: yes

#640 Tweaks to pubspec example
  src/tools/pub/pubspec.md
Labels: cla: yes

#641 chore: only analyze and test under 1.x
  .gitignore
  .travis.yml
Labels: cla: yes

#642 Examples: rename constants pi, utf8, json, etc
  .gitignore
  examples/httpserver/bin/basic_writer_client.dart
  examples/httpserver/bin/basic_writer_server.dart
  examples/httpserver/bin/note_server.dart
  examples/httpserver/bin/number_guesser.dart
  examples/httpserver/test/httpserver_test.dart
  examples/misc/lib/effective_dart/usage_bad.dart
  examples/misc/lib/effective_dart/usage_good.dart
  examples/misc/lib/library_tour/async/stream.dart
  examples/misc/test/language_tour/classes_test.dart
  examples/misc/test/library_tour/convert_test.dart
  examples/misc/test/library_tour/io_test.dart
  examples/misc/test/library_tour/math_test.dart
  examples/misc/test/tutorial/futures_test.dart
  examples/strong/lib/dart_1_my_list_hello_world.dart
  scripts/youtube.dart
  src/_articles/libraries/broadcast-streams.md
  src/_articles/libraries/converters-and-codecs.md
  src/_guides/language/effective-dart/usage.md
  src/_guides/language/language-tour.md
  src/_guides/libraries/library-tour.md
  src/_tutorials/dart-vm/cmdline.md
  src/_tutorials/dart-vm/httpserver.md
  src/_tutorials/language/streams.md
  src/dart-vm/dart-by-example/index.md
  src/dart-vm/io-library-tour.md
  src/install/archive/web/download_archive.dart
Labels: Infrastructure, Tests, cla: yes

#644 Fix popovers in non-frontpage pages
  src/_tutorials/dart-vm/cmdline.md
  src/_tutorials/libraries/shared-pkgs.md
Labels: Infrastructure, cla: yes

#648 Update language-tour.md
  src/_guides/language/language-tour.md
Labels: cla: yes

#652 Add v1 to .firebaserc
  .firebaserc
Labels: cla: yes

#669 Drop use of "new" from main frontpage example
  examples/misc/lib/pi_monte_carlo.dart
  examples/misc/test/pi_test.dart
  scripts/analyze-and-test-examples.sh
  src/_assets/stylesheets/_overwrites.scss
  src/_main-example.html
  src/index.html
Labels: cla: yes

#670 Remove Dart Tips videos
  firebase.json
  src/resources/dart-tips/dart-tips-1.md
  src/resources/dart-tips/dart-tips-10.md
  src/resources/dart-tips/dart-tips-11.md
  src/resources/dart-tips/dart-tips-2.md
  src/resources/dart-tips/dart-tips-3.md
  src/resources/dart-tips/dart-tips-4.md
  src/resources/dart-tips/dart-tips-5.md
  src/resources/dart-tips/dart-tips-6.md
  src/resources/dart-tips/dart-tips-7.md
  src/resources/dart-tips/dart-tips-8.md
  src/resources/dart-tips/dart-tips-9.md
  src/resources/dart-tips/index.md
  src/resources/index.md
Labels: cla: yes

#674 chore: manually skip test using optional new syntax
  scripts/analyze-and-test-examples.sh
Labels: Tests, cla: yes

#672 chore: use code-excerpter npm package
  .travis.yml
  package.json
  scripts/install.sh
  scripts/refresh-code-excerpts.sh
Labels: Infrastructure, cla: yes

#675 chore: use code-excerpter npm package (1.x)
  .travis.yml
  package.json
  scripts/install.sh
  scripts/refresh-code-excerpts.sh
Labels: Infrastructure, cla: yes

#678 Added Flutter
  src/community/who-uses-dart.md
Labels: cla: yes

#677 Dart 2 changes to the language tour
  examples/misc/analyzer-2-results.txt
  examples/misc/lib/language_tour/built_in_types.dart
  examples/misc/lib/language_tour/classes/misc.dart
  examples/misc/lib/language_tour/classes/point_alt.dart
  examples/misc/lib/language_tour/generics/base_class.dart
  examples/misc/lib/language_tour/variables.dart
  examples/misc/test/language_tour/basic_test.dart
  examples/misc/test/language_tour/generics_test.dart
  examples/misc/test/language_tour/variables_test.dart
  src/_guides/language/language-tour.md
Labels: cla: no

#687 Update samples page, remove cookbook
  firebase.json
  src/_samples/index.md
  src/dart-vm/dart-by-example/README.md
  src/dart-vm/dart-by-example/index.md
  src/dart-vm/index.md
  src/dart-vm/io-library-tour.md
Labels: cla: yes

#688 Add banner to Effective Dart
  src/_guides/language/effective-dart/design.md
  src/_guides/language/effective-dart/documentation.md
  src/_guides/language/effective-dart/index.md
  src/_guides/language/effective-dart/style.md
  src/_guides/language/effective-dart/usage.md
  src/_includes/effective-dart-banner.html
Labels: cla: yes

#691 Minimal changes to Dart VM tutorials
  src/_includes/tutorial-banner.html
  src/_tutorials/dart-vm/cmdline.md
  src/_tutorials/dart-vm/get-started.md
  src/_tutorials/dart-vm/httpserver.md
Labels: cla: yes

#695 Remove unused "runtests" files.
  runtests.bat
  runtests.sh
Labels: cla: yes

#665 Updating front page with Dart 2 core tenets
  src/index.html
Labels: cla: yes

#694 No more "strong mode"
  examples/strong/analyzer-2-results.txt
  examples/strong/lib/strong_analysis.dart
  examples/strong/test/strong_test.dart
  firebase.json
  src/_guides/language/analysis-options.md
  src/_guides/language/index.md
  src/_guides/language/sound-dart.md
  src/_guides/language/sound-faq.md
  src/_guides/language/sound-problems.md
  src/_includes/dart-tips-caveat.html
  src/dart-2.md
  src/faq.md
Labels: cla: yes

#699 Remove most occurrences of "dartium"
  src/_articles/dart-vm/benchmarking.md
  src/_articles/dart-vm/index.md
  src/_articles/dart-vm/io.md
  src/_articles/dart-vm/native-extensions.md
  src/_articles/dart-vm/numeric-computation.md
  src/_articles/dart-vm/reflection-with-mirrors.md
  src/_articles/dart-vm/simd.md
  src/_articles/index.md
  src/_articles/language/await-async.md
  src/_articles/language/beyond-async.md
  src/_articles/language/emulating-functions.md
  src/_articles/language/mixins.md
  src/_articles/libraries/broadcast-streams.md
  src/_articles/libraries/converters-and-codecs.md
  src/_articles/libraries/creating-streams.md
  src/_articles/libraries/serialization.md
  src/_articles/libraries/zones.md
  src/_includes/article_index_warning.md
  src/_includes/dartium-2.0.html
  src/_includes/tools/jetbrains-reporting-issues.html
  src/diagrams/tutorials/get-started/dartvm.graffle
  src/diagrams/tutorials/get-started/dartvm.graffle/data.plist
  src/diagrams/tutorials/get-started/dartvm.graffle/image2.png
  src/install/archive/index.md
  src/install/index.md
  src/install/linux.md
  src/install/mac.md
  src/install/windows.md
  src/tools/index.md
  src/tools/jetbrains-plugin.md
  src/tools/pub/assets-and-transformers.md
Labels: cla: yes

#698 Copy-edit the Effective Dart intro, clarify definitions
  src/_guides/language/effective-dart/index.md
Labels: cla: yes

#704 Add a couple of guidelines for using optional parameters.
  examples/misc/lib/effective_dart/usage_bad.dart
  examples/misc/lib/effective_dart/usage_good.dart
  src/_guides/language/effective-dart/toc.md
  src/_guides/language/effective-dart/usage.md
Labels: cla: yes

#705 Add a guideline for naming type parameters.
  examples/misc/lib/effective_dart/design_good.dart
  src/_guides/language/effective-dart/design.md
  src/_guides/language/effective-dart/style.md
  src/_guides/language/effective-dart/toc.md
Labels: cla: yes

#707 Remove /performance
  firebase.json
  src/faq.md
  src/performance.md
Labels: cla: yes

#706 [1.x] Pub transformer warning
  _config.yml
  src/_includes/tools/jetbrains-reporting-issues.html
  src/_includes/tools/transformers-going-away.md
  src/tools/pub/assets-and-transformers.md
  src/tools/pub/cmd/index.md
  src/tools/pub/glossary.md
  src/tools/pub/index.md
  src/tools/pub/transformers/aggregate.md
  src/tools/pub/transformers/examples.md
  src/tools/pub/transformers/index.md
  src/tools/pub/transformers/lazy-transformer.md
Labels: cla: yes

#708 Improve Effective Dart guidelines for doc comments.
  examples/misc/lib/effective_dart/docs_bad.dart
  examples/misc/lib/effective_dart/docs_good.dart
  src/_guides/language/effective-dart/documentation.md
  src/_guides/language/effective-dart/toc.md
Labels: cla: yes

#703 Remove pub build/serve & transformers
  _config.yml
  firebase.json
  src/_assets/page_assets/tools/assets-and-transformers.png
  src/_guides/libraries/create-library-packages.md
  src/_guides/libraries/private-files.md
  src/_includes/flutter-packages.md
  src/_includes/tools/pub-was-a-builder.md
  src/dart-2.md
  src/diagrams/tools/assets-and-transformers.graffle
  src/tools/pub/assets-and-transformers.md
  src/tools/pub/cmd/index.md
  src/tools/pub/cmd/pub-get.md
  src/tools/pub/cmd/pub-run.md
  src/tools/pub/glossary.md
  src/tools/pub/index.md
  src/tools/pub/obsolete.md
  src/tools/pub/package-layout.md
  src/tools/pub/pubspec.md
  src/tools/pub/transformers/aggregate.md
  src/tools/pub/transformers/examples.md
  src/tools/pub/transformers/index.md
  src/tools/pub/transformers/lazy-transformer.md
Labels: cla: yes

#710 Remove synonyms from Dart 2 version of dartlang.org
  src/_assets/stylesheets/_synonyms.scss
  src/_assets/stylesheets/main.scss
  src/resources/index.md
  src/resources/synonyms/assets/csharp-samples.xml
  src/resources/synonyms/assets/dart-samples.xml
  src/resources/synonyms/assets/dart.js
  src/resources/synonyms/assets/es6-samples.xml
  src/resources/synonyms/assets/java-samples.xml
  src/resources/synonyms/assets/js-samples.xml
  src/resources/synonyms/assets/prettify.js
  src/resources/synonyms/assets/python-samples.xml
  src/resources/synonyms/assets/synonyms.dart
  src/resources/synonyms/assets/synonyms.dart.js
  src/resources/synonyms/assets/synonyms.dart.js.map
  src/resources/synonyms/assets/synonyms.dart.precompiled.js
  src/resources/synonyms/assets/transform.xslt
  src/resources/synonyms/assets/typescript-samples.xml
  src/resources/synonyms/index.md
Labels: cla: yes

#709 Add guideline for List.from() and toList().
  examples/misc/test/effective_dart_test.dart
  src/_guides/language/effective-dart/toc.md
  src/_guides/language/effective-dart/usage.md
Labels: cla: yes

#716 Update assert and checked mode info
  src/_data/pkg-vers.json
  src/_guides/language/language-tour.md
  src/_guides/language/sound-problems.md
  src/dart-2.md
  src/dart-vm/tools/dart-vm.md
  src/dart-vm/tools/index.md
  src/tools/dartpad.md
Labels: cla: yes

#718 Add migration process to /dart-2
  src/dart-2.md
Labels: cla: yes

#719 Fix build
  examples/misc/lib/effective_dart/docs_good.dart
  src/_guides/language/effective-dart/documentation.md
Labels: cla: yes

#720 Effective dart: documentation, reintroduce triple backtick blocks
  examples/misc/lib/effective_dart/docs_good.dart
  src/_guides/language/effective-dart/documentation.md
  src/_tutorials/dart-vm/httpserver.md
Labels: cla: yes

#723 Remove whitespace guidelines. Dartfmt is the style guide.
  examples/misc/lib/effective_dart/style_good.dart
  src/_guides/language/effective-dart/documentation.md
  src/_guides/language/effective-dart/style.md
  src/_guides/language/effective-dart/toc.md
Labels: cla: yes

#725 Refresh code excerpts to remove excess code
  src/_guides/language/effective-dart/documentation.md
Labels: cla: yes

#726 chore: add firebase dartlang-org-staging-1 project
  .firebaserc
Labels: Infrastructure, cla: yes

#715 Update guidelines on doc comments.
  examples/misc/lib/effective_dart/docs_bad.dart
  examples/misc/lib/effective_dart/docs_good.dart
  src/_guides/language/effective-dart/documentation.md
  src/_guides/language/effective-dart/toc.md
Labels: cla: yes

#712 Add guidelines for parts and imports.
  examples/misc/lib/effective_dart/my_library.dart
  examples/misc/lib/effective_dart/some/other/file.dart
  examples/misc/lib/effective_dart/some/other/file_2.dart
  src/_guides/language/effective-dart/toc.md
  src/_guides/language/effective-dart/usage.md
Labels: cla: yes

#729 Redirects and link tweaks
  firebase.json
  src/_articles/dart-vm/benchmarking.md
  src/_guides/language/sound-problems.md
Labels: cla: yes
