Repository dart-lang/site-www, pull requests merged in 2018-02, with the labels that each got.

#567 Add "Invalid cast" section to strong mode troubleshooting
  src/_assets/stylesheets/main.scss
  src/_guides/language/sound-problems.md
Labels: cla: yes

#568 Update type cast errors section
  src/_guides/language/sound-problems.md
Labels: cla: no

#574 chore: travis use dart env; upgrade ruby and gems
  .travis.yml
  Gemfile
  Gemfile.lock
  examples/dart_test.yaml
  examples/misc/dart_test.yaml
  scripts/env-set.sh
  scripts/get-ruby.sh
  scripts/refresh-code-excerpts.sh
Labels: Infrastructure, cla: yes

#575 chore: define `travischrome` platform for testing on Travis
  examples/dart_test.yaml
  scripts/analyze-and-test-examples.sh
Labels: Infrastructure, cla: yes

#581 chore: fixes due to breaking changes in fontawesome 5.x
  .travis.yml
  src/_guides/get-started.md
  src/_includes/page-footer.html
  src/_includes/page-github-links.html
Labels: Design, cla: yes

#579 Add an example/solution for uses_dynamic_as_bottom
  src/_guides/language/sound-problems.md
Labels: cla: yes

#582 Update sound-problems.md
  src/_guides/language/sound-problems.md
Labels: cla: yes

#583 Examples: fix type error reported by Dart 2 analyzer
  examples/misc/lib/samples/spacecraft.dart
  examples/misc/test/samples_test.dart
Labels: Examples, cla: yes

#585 Examples: run analyzer and tests under Dart 2, and other script tweaks
  .travis.yml
  examples/misc/analyzer-2-results.txt
  scripts/analyze-and-test-examples.sh
Labels: Infrastructure, cla: yes

#586 Enable no-implicit-casts: bug fix, and non-user-visible code changes
  examples/httpserver/bin/basic_writer_server.dart
  examples/httpserver/bin/note_server.dart
  examples/httpserver/bin/number_guesser.dart
  examples/httpserver/web/note_client.dart
  examples/misc/lib/effective_dart/design_bad.dart
  examples/misc/lib/effective_dart/design_good.dart
  examples/misc/lib/effective_dart/docs_bad.dart
  examples/misc/lib/effective_dart/docs_good.dart
  examples/misc/lib/effective_dart/style_good.dart
  examples/misc/lib/effective_dart/usage_bad.dart
  examples/misc/lib/effective_dart/usage_good.dart
  examples/misc/lib/language_tour/async.dart
  examples/misc/lib/language_tour/control_flow.dart
  examples/misc/lib/language_tour/operators.dart
  examples/misc/lib/library_tour/async/stream.dart
  examples/misc/lib/library_tour/io/http_server.dart
  examples/misc/lib/samples/spacecraft.dart
  examples/misc/lib/tutorial/daily_news.dart
  examples/misc/test/language_tour/classes_test.dart
  examples/util/lib/ellipsis.dart
  scripts/dartfmt.sh
  scripts/refresh-code-excerpts.sh
  src/_guides/language/effective-dart/design.md
  src/_guides/language/effective-dart/usage.md
  src/_guides/language/language-tour.md
  src/_tutorials/dart-vm/httpserver.md
  src/_tutorials/language/futures.md
  src/dart-vm/io-library-tour.md
Labels: Tests, cla: yes

#587 Enable no-implicit-casts: code fixes that are user visible
  examples/analysis_options.yaml
  examples/misc/analyzer-1-results.txt
  examples/misc/lib/language_tour/classes/point.dart
  examples/misc/lib/language_tour/classes/point_alt.dart
  examples/misc/lib/language_tour/classes/point_with_distance_field.dart
  examples/misc/test/language_tour/async_test.dart
  src/_guides/language/language-tour.md
Labels: Tests, cla: yes

#589 chore: support comments in expected analyzer output files
  examples/misc/analyzer-1-results.txt
  scripts/analyze-and-test-examples.sh
Labels: Infrastructure, cla: yes

#595 Update dart-2 page for Flutter and --preview-dart-2
  src/dart-2.md
Labels: cla: yes

#592 Reinstate Install Dart button + warn Flutter devs
  src/_assets/stylesheets/main.scss
  src/index.html
  src/install/index.md
Labels: Design, cla: yes

#597 Add list of Dart 2 resources
  src/dart-2.md
Labels: cla: yes

#599 Cross-link to Flutter's Dart 2 page
  src/dart-2.md
Labels: cla: yes

#601 Add Flutter migration instructions to list of resources
  src/dart-2.md
Labels: cla: yes

#603 Strong mode code excerpt tests for fix-it page
  examples/strong/analyzer-1-results.txt
  examples/strong/analyzer-2-results.txt
  examples/strong/lib/animal.dart
  examples/strong/lib/animal_bad.dart
  examples/strong/lib/common_fixes_analysis.dart
  examples/strong/lib/common_problems_analysis.dart
  examples/strong/lib/covariant.dart
  examples/strong/lib/strong_analysis.dart
  examples/strong/test/strong_test.dart
  scripts/analyze-and-test-examples.sh
  src/_assets/stylesheets/_code.scss
  src/_guides/language/sound-dart.md
  src/_guides/language/sound-problems.md
Labels: Examples, Infrastructure, SoundDart, Tests, cla: yes

#605 Strong mode page: show actual analyzer error
  src/_guides/language/sound-dart.md
Labels: SoundDart, cla: yes

#607 Strong mode prose tweak (followup)
  src/_guides/language/sound-dart.md
Labels: SoundDart, cla: yes

#610 Announce Dart 2 on frontpage
  src/_assets/stylesheets/main.scss
  src/_includes/banner-fp.html
  src/_includes/banner-fp.md
  src/index.html
Labels: cla: yes

#613 Markdown syntax fix for dart-tips-6
  src/resources/dart-tips/dart-tips-6.md
Labels: cla: yes

#616 Remove sonardesign.com links
  src/community/who-uses-dart.md
Labels: cla: yes
