Repository dart-lang/site-www, pull requests merged in 2018-04, with the labels that each got.

#731 Update DartPad page
  src/tools/dartpad.md
  src/tools/images/DartPadWindow.png
Labels: cla: yes

#732 Add subsection for publish_to
  src/tools/pub/pubspec.md
Labels: cla: yes

#733 chore: pin SDK version to 2-dev.43
  .travis.yml
Labels: Infrastructure, cla: yes

#728 Redo guidelines around getters and setters.
  examples/misc/lib/effective_dart/design_bad.dart
  examples/misc/lib/effective_dart/design_good.dart
  src/_guides/language/effective-dart/design.md
  src/_guides/language/effective-dart/toc.md
Labels: cla: yes

#730 Better async example.
  examples/misc/lib/effective_dart/usage_bad.dart
  examples/misc/lib/effective_dart/usage_good.dart
  src/_guides/language/effective-dart/usage.md
Labels: cla: yes

#734 Tweak style guidelines.
  src/_guides/language/effective-dart/style.md
  src/_guides/language/effective-dart/toc.md
Labels: cla: yes

#727 Refactor Install page before moving a copy to webdev
  _config.yml
  firebase.json
  src/_assets/images/installer-screenshot-no.png
  src/_assets/javascripts/_os-tabs.js
  src/_assets/javascripts/main.js
  src/_assets/javascripts/vendor/jquery-1.12.3.min.js
  src/_assets/javascripts/vendor/jquery-3.3.1.js
  src/_assets/javascripts/vendor/jquery-3.3.1.min.js
  src/_assets/stylesheets/_os-tabs.scss
  src/_assets/stylesheets/main.scss
  src/_data/side-nav.yml
  src/_guides/platforms.md
  src/_includes/configure-path.html
  src/_tutorials/dart-vm/cmdline.md
  src/_tutorials/dart-vm/get-started.md
  src/dart-2.md
  src/dart-vm/index.md
  src/dart-vm/tools/index.md
  src/install.md
  src/install/_debian.html
  src/install/index.md
  src/install/linux.md
  src/install/mac.md
  src/install/windows.md
  src/tools/index.md
  src/tools/jetbrains-plugin.md
  src/tools/pub/cmd/pub-get.md
  src/tools/pub/environment-variables.md
  src/tools/pub/glossary.md
  src/tools/pub/index.md
  src/tools/pub/installing.md
  src/tools/sdk.md
  src/tools/sdk/_linux.md
  src/tools/sdk/_mac.md
  src/tools/sdk/_windows.md
  src/tools/sdk/archive/_README.md
  src/tools/sdk/archive/_archives_table.html
  src/tools/sdk/archive/assets/install.js
  src/tools/sdk/archive/index.md
  src/tools/sdk/archive/out/web/download_archive.dart.js
  src/tools/sdk/archive/pubspec.yaml
  src/tools/sdk/archive/web/download_archive.dart
  src/tools/sdk/index.md
Labels: InstallDart, cla: yes

#737 Delete assets related to the old flowchart
  README.md
  src/_assets/stylesheets/_overwrites.scss
  src/_guides/images/get-started-flowchart.png
  src/_guides/images/get-started-flowchart.svg
Labels: cla: yes

#739 Remove API Reference submenu items from sidenav
  src/_data/side-nav.yml
  src/_guides/libraries/index.md
  src/dart-vm/index.md
Labels: Design, cla: yes

#740 Reminder to add SDK bin to PATH when manually installing SDK
  src/tools/sdk/index.md
Labels: cla: yes

#741 Add guidelines about implementing interfaces.
  src/_guides/language/effective-dart/design.md
  src/_guides/language/effective-dart/toc.md
Labels: cla: yes

#744 chore: don't run dartfmt over files inside `build`
  scripts/dartfmt.sh
Labels: Infrastructure, cla: yes

#747 Upgrade to SDK 2-dev.46 (unpinning the build)
  .travis.yml
  examples/strong/test/strong_test.dart
  src/_data/pkg-vers.json
Labels: cla: yes

#724 Dart language-version menu for switching between site versions
  _config.yml
  src/_assets/stylesheets/main.scss
  src/_includes/_version-menu-items.html
  src/_includes/navigation-main.html
Labels: cla: yes

#742 Dart VM, Get Started updates
  examples/misc/lib/vm_get_started.dart
  src/_assets/stylesheets/main.scss
  src/_tutorials/dart-vm/get-started.md
Labels: Design, Examples, Tests, cla: yes

#750 Add `new` back to the homepage example
  examples/misc/lib/pi_monte_carlo.dart
  examples/misc/test/pi_test.dart
  src/_main-example.html
Labels: cla: yes

#754 Simplify /codelabs
  src/_codelabs/index.md
Labels: cla: yes

#752 Set prev-url to main site for now
  _config.yml
Labels: cla: yes

#758 chore: remove remaining traces of using site-webdev as a sibling repo
  .travis.yml
  CONTRIBUTING.md
  README.md
  scripts/env-set.sh
  scripts/install-webdev.sh
  scripts/write-ci-info.sh
Labels: Infrastructure, cla: yes

#762 Add /tools/pub/obsolete to the 1.x site
  src/tools/pub/obsolete.md
Labels: cla: yes

#763 Add guideline for preferring the positive form of boolean names.
  examples/misc/lib/effective_dart/design_bad.dart
  examples/misc/lib/effective_dart/design_good.dart
  src/_guides/language/effective-dart/design.md
Labels: cla: yes

#769 [1.x] Fix pub cmd 404
  src/tools/pub/cmd/index.md
Labels: cla: yes

#753 [1.x] Dart language-version menu for switching between site versions
  _config.yml
  src/_assets/stylesheets/main.scss
  src/_data/pkg-vers.json
  src/_includes/_version-menu-items.html
  src/_includes/banner-fp.md
  src/_includes/banner.html
  src/_includes/navigation-main.html
Labels: cla: yes

#770 [1.x] Publish 1.x site on v1 server
  .travis.yml
  _config.yml
  src/_includes/banner.html
Labels: Infrastructure, cla: yes

#765 Dart 2 site banner announcing Dart 2
  _config.yml
  src/_includes/_version-menu-items.html
  src/_includes/banner-fp.md
  src/_includes/banner.html
  src/_includes/navigation-main.html
  src/_layouts/default.html
  src/_plugins/regex_replace_filter.rb
Labels: cla: yes

#771 chore: update deploy script to match webdev version
  deploy/deploy-firebase.sh
Labels: Infrastructure, cla: yes

#772 Publish Dart 2 site on www.dartlang.org
  .travis.yml
  _config.yml
  src/_includes/banner.html
Labels: Infrastructure, cla: yes

#774 Update Effective Dart banner
  src/_includes/effective-dart-banner.html
Labels: cla: yes

#775 /dart-2: Add better intros, change title
  src/_includes/banner.html
  src/_includes/navigation-main.html
  src/dart-2.md
  src/tools/pub/obsolete.md
Labels: cla: yes, ⚠ WIP

#777 Add info on migrating packages
  src/dart-2.md
Labels: cla: yes

#778 [1.x] Gut /dart-2
  src/dart-2.md
Labels: cla: yes

#779 chore: ignore site-shared
  .gitignore
Labels: Infrastructure, cla: yes

#766 Update guideline for "=>" now that it works for void.
  examples/misc/lib/effective_dart/usage_bad.dart
  examples/misc/lib/effective_dart/usage_good.dart
  src/_guides/language/effective-dart/usage.md
Labels: cla: yes

#780 Danbrotherston patch 2
  src/tools/pub/dependencies.md
Labels: cla: yes

#781 Update boolean info in the language tour
  src/_guides/language/language-tour.md
Labels: cla: yes

#783 Add a bit more info to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla: yes

#782 json.encode/decode -> jsonEncode/jsonDecode
  examples/httpserver/bin/basic_writer_client.dart
  examples/httpserver/bin/basic_writer_server.dart
  examples/misc/test/language_tour/classes_test.dart
  examples/misc/test/library_tour/convert_test.dart
  scripts/youtube.dart
  src/_guides/language/language-tour.md
  src/_guides/libraries/library-tour.md
  src/_tutorials/dart-vm/httpserver.md
Labels: cla: yes

#785 Add codelab link to /tutorials
  src/_tutorials/index.md
Labels: cla: yes

#790 Upgrade to SDK 2-dev.48, with minor code changes
  .travis.yml
  examples/httpserver/bin/note_server.dart
  examples/httpserver/web/note_client.dart
  src/_data/pkg-vers.json
Labels: Examples, Infrastructure, cla: yes

#791 Effective dart tests: slight test refactoring
  examples/misc/test/effective_dart_test.dart
Labels: EffectiveDart, Tests, cla: yes

#743 Revise the guidelines on type annotations.
  examples/misc/lib/effective_dart/design_bad.dart
  examples/misc/lib/effective_dart/design_good.dart
  examples/misc/lib/effective_dart/usage_bad.dart
  examples/misc/lib/effective_dart/usage_good.dart
  src/_guides/language/effective-dart/design.md
  src/_guides/language/effective-dart/toc.md
  src/_guides/language/effective-dart/usage.md
Labels: cla: yes

#809 Apply Lasse's feedback from #743.
  examples/misc/lib/effective_dart/design_good.dart
  src/_guides/language/effective-dart/design.md
  src/_guides/language/effective-dart/toc.md
Labels: cla: yes

#805 Delete /tools/faq
  firebase.json
  src/faq.md
  src/tools/faq.md
  src/tools/pub/index.md
Labels: cla: yes

#807 Let readers know that all books cover Dart 1.x
  src/resources/books.md
Labels: cla: yes

#811 Update AngularDart link and description
  src/community/who-uses-dart.md
Labels: cla: yes

#808 More "Effective Dart" guidelines.
  examples/misc/lib/effective_dart/design_bad.dart
  examples/misc/lib/effective_dart/design_good.dart
  examples/misc/lib/effective_dart/usage_bad.dart
  examples/misc/lib/effective_dart/usage_good.dart
  src/_guides/language/effective-dart/design.md
  src/_guides/language/effective-dart/toc.md
  src/_guides/language/effective-dart/usage.md
Labels: cla: yes

#820 Update auto-const discussion
  src/_guides/language/language-tour.md
Labels: cla: yes

#813 Tutorial(streams): update for Dart 2 and analayze/test code
  examples/misc/lib/tutorial/cat_no_hash.dart
  examples/misc/lib/tutorial/misc.dart
  examples/misc/lib/tutorial/stream_interface.dart
  examples/misc/lib/tutorial/sum_stream.dart
  examples/misc/lib/tutorial/sum_stream_with_catch.dart
  examples/misc/test/tutorial/streams_test.dart
  src/_tutorials/dart-vm/cmdline.md
  src/_tutorials/dart-vm/httpserver.md
  src/_tutorials/language/futures.md
  src/_tutorials/language/streams.md
  src/_tutorials/libraries/shared-pkgs.md
Labels: Examples, Tests, cla: yes

#821 [1.x] chore: pin SDK at 1.24.3
  .travis.yml
Labels: Infrastructure, cla: yes

#822 chore: update SDK version in pkg-vers.json
  src/_data/pkg-vers.json
Labels: cla: yes

#824 Upgrade to Dart SDK 2-dev.51
  .travis.yml
  examples/httpserver/pubspec.yaml
  examples/misc/pubspec.yaml
  examples/strong/pubspec.yaml
  examples/util/pubspec.yaml
  src/_data/pkg-vers.json
Labels: cla: yes

#816 Added info for checking DartPad's version
  src/tools/dartpad.md
Labels: cla: yes
