Repository dart-lang/site-www, pull requests merged in 2018-07, with the labels that each got.

#983 Redirect old social media image URLs to current image
  firebase.json
Labels: cla: yes

#978 Clarify scope and readership of "Mixins in Dart"
  src/_articles/language/mixins.md
  src/_guides/language/language-tour.md
Labels: Articles, cla: yes

#984 Link to site.webdev rather than site.dev-webdev
  src/_guides/language/language-tour.md
  src/dart-2.md
  src/install.md
  src/tools/index.md
  src/tools/pub/obsolete.md
Labels: cla: yes

#986 Update shared-pkgs tutorial
  src/_tutorials/libraries/shared-pkgs.md
Labels: cla: yes

#981 C# allows multiple top level classes
  src/_guides/language/effective-dart/design.md
Labels: cla: yes

#987 Upgrade SDK to 2-dev.67
  .travis.yml
  examples/httpserver/pubspec.yaml
  examples/misc/pubspec.yaml
  examples/misc/test/language_tour/generics_test.dart
  examples/misc/test/language_tour/operators_test.dart
  examples/strong/pubspec.yaml
  examples/util/pubspec.yaml
  src/_data/pkg-vers.json
  src/_guides/language/language-tour.md
Labels: cla: yes

#988 chore: update gems, drop buggy custom plugin, use std jekyll fields
  Gemfile.lock
  _config.yml
  src/_articles/dart-vm/benchmarking.md
  src/_articles/dart-vm/index.md
  src/_articles/dart-vm/io.md
  src/_articles/dart-vm/native-extensions.md
  src/_articles/dart-vm/numeric-computation.md
  src/_articles/dart-vm/reflection-with-mirrors.md
  src/_articles/dart-vm/simd.md
  src/_articles/index.md
  src/_articles/language/await-async.md
  src/_articles/language/beyond-async.md
  src/_articles/language/emulating-functions.md
  src/_articles/language/index.md
  src/_articles/language/mixins.md
  src/_articles/libraries/broadcast-streams.md
  src/_articles/libraries/converters-and-codecs.md
  src/_articles/libraries/creating-streams.md
  src/_articles/libraries/index.md
  src/_articles/libraries/serialization.md
  src/_articles/libraries/zones.md
  src/_includes/article_summary.html
  src/_plugins/filters.rb
Labels: Infrastructure, cla: yes

#989 Document @required
  examples/misc/lib/language_tour/functions.dart
  src/_guides/language/language-tour.md
Labels: LanguageTour, cla: yes

#991 Add note about whereType implementation status
  src/_guides/language/effective-dart/usage.md
Labels: cla: yes

#992 Link to newer Chinese clone of this site
  src/community/index.md
Labels: cla: yes

#994 Redirect /web-ui/observables
  firebase.json
Labels: cla: yes

#998 Upgrade to 2-dev.68 and adjust Analysis options page
  .travis.yml
  deploy/effective-dart-rules/analysis_options.yaml
  examples/httpserver/pubspec.yaml
  examples/misc/pubspec.yaml
  examples/strong/pubspec.yaml
  examples/util/pubspec.yaml
  src/_data/pkg-vers.json
  src/_guides/language/analysis-options.md
  src/_guides/language/sound-problems.md
Labels: cla: yes

#1000 Update Dart 2 constraint guidance for packages
  src/dart-2.md
Labels: cla: yes

#1002 Set SDK max to <3.0.0 in examples and adjust prose
  examples/httpserver/pubspec.yaml
  examples/misc/pubspec.yaml
  examples/strong/pubspec.yaml
  examples/util/pubspec.yaml
  pubspec.yaml
  src/_tutorials/libraries/shared-pkgs.md
  src/tools/pub/pubspec.md
Labels: cla: yes

#1004 SDK max to 3.0.0, some followup edits
  src/dart-2.md
  src/tools/pub/pubspec.md
Labels: cla: yes

#990 Minor fixes in docs
  src/_guides/language/effective-dart/style.md
  src/_guides/language/language-tour.md
Labels: cla: yes

#1005 Fix the build
  examples/misc/lib/effective_dart/style_bad.dart
Labels: cla: yes

#1007 Minor updates to shared-pkgs tutorial
  src/_tutorials/libraries/shared-pkgs.md
Labels: cla: yes

#1008 Upgrade to SDK 2-dev.69
  .travis.yml
  examples/httpserver/pubspec.yaml
  examples/misc/pubspec.yaml
  examples/strong/pubspec.yaml
  examples/util/pubspec.yaml
  pubspec.yaml
  src/_data/pkg-vers.json
  src/_tutorials/libraries/shared-pkgs.md
Labels: Infrastructure, cla: yes

#1014 Single quotes on raw string example in lang tour
  examples/misc/lib/language_tour/built_in_types.dart
  src/_guides/language/language-tour.md
Labels: cla: yes

#1015 Fix typos: pub.dartlang.com -> pub.dartlang.org
  src/_guides/libraries/create-library-packages.md
  src/tools/pub/pubspec.md
Labels: cla: yes

#1006 Add prefix item to Effective Dart
  src/_guides/language/effective-dart/style.md
  src/_guides/language/effective-dart/toc.md
Labels: cla: yes

#1016 Add deprecation hints & new/const removal to /dart-2
  src/dart-2.md
  src/tools/pub/dependencies.md
Labels: cla: yes

#1020 chore: support use of fixed site page timestamp
  _config_now.yml
  scripts/serve_local.sh
  src/_includes/page-footer.html
  src/sitemap.xml
Labels: Infrastructure, cla: yes

#1022 Make article obsolescence warning less scary
  src/_includes/article_index_warning.md
  src/_includes/page-header.html
Labels: cla: yes

#1019 Change remaining prominent uses of "Dart VM" to "server-side Dart"
  src/_articles/index.md
  src/_articles/language/index.md
  src/_articles/libraries/index.md
  src/_guides/get-started.md
  src/_guides/index.md
  src/_guides/libraries/useful-libraries.md
  src/_guides/testing.md
  src/_tutorials/dart-vm/get-started.md
  src/_tutorials/dart-vm/index.md
  src/_tutorials/index.md
  src/dart-2.md
  src/dart-vm/io-library-tour.md
  src/dart-vm/tools/index.md
  src/install.md
  src/tools/index.md
Labels: cla: yes

#1023 chore: fix background color on pages marked obsolete
  src/_assets/stylesheets/main.scss
Labels: cla: yes

#1025 Update serialization article note
  src/_articles/libraries/serialization.md
Labels: cla: yes

#1026 Analysis options: add lints for unnecessary cont and new, replace symlinks with `include`
  deploy/effective-dart-rules/analysis_options.yaml
  examples/analysis_options.yaml
  examples/httpserver/analysis_options.yaml
  examples/misc/analysis_options.yaml
  examples/misc/lib/effective_dart/usage_bad.dart
  examples/misc/test/language_tour/browser_test.dart
  examples/misc/test/language_tour/classes_test.dart
  examples/misc/test/pi_test.dart
  examples/strong/analysis_options.yaml
  examples/util/analysis_options.yaml
Labels: cla: yes

#1027 Add Chinese translation to "Chinese version of this site"
  src/community/index.md
Labels: cla: yes

#1033 Add link to Filip's article
  src/dart-2.md
Labels: cla: yes

#1035 Upgrade SDK to 2-dev.69.4
  .travis.yml
  examples/httpserver/pubspec.yaml
  examples/misc/pubspec.yaml
  examples/strong/pubspec.yaml
  examples/util/pubspec.yaml
  src/_data/pkg-vers.json
  src/_tutorials/libraries/shared-pkgs.md
Labels: cla: yes

#1034 Add notes to articles
  src/_articles/dart-vm/benchmarking.md
  src/_articles/dart-vm/numeric-computation.md
  src/_articles/dart-vm/simd.md
  src/_articles/libraries/serialization.md
Labels: cla: yes

#1037 Upgrade SDK to 2-dev.69.5
  .travis.yml
  examples/httpserver/pubspec.yaml
  examples/misc/pubspec.yaml
  examples/strong/pubspec.yaml
  examples/util/pubspec.yaml
  src/_data/pkg-vers.json
  src/_tutorials/libraries/shared-pkgs.md
Labels: cla: yes
