Repository dart-lang/site-www, pull requests merged in 2018-08, with the labels that each got.

#1040 Library tour: drop sentence mentioning import prefix
  src/_guides/libraries/library-tour.md
Labels: LibraryTour, cla: yes

#1042 Dartpad prose updates
  src/_guides/libraries/library-tour.md
  src/tools/dartpad.md
Labels: Dart2, cla: yes

#1043 Library tour: generic list example gives static error, not warning
  examples/misc/analyzer-2-results.txt
  examples/misc/lib/library_tour/core/collections.dart
  examples/misc/test/library_tour/core_test.dart
  scripts/dartfmt.sh
  src/_guides/libraries/library-tour.md
Labels: Dart2, LibraryTour, cla: yes

#1046 chore: drop unused example code using deprecated `@proxy` annotation
  examples/misc/lib/language_tour/classes/proxy.dart
  examples/misc/lib/language_tour/classes/proxy_alt.dart
  examples/misc/test/language_tour/classes_test.dart
Labels: Dart2, cla: yes

#1047 Example(whereType): add test
  examples/misc/lib/effective_dart/usage_good.dart
  examples/misc/test/effective_dart_test.dart
  src/_guides/language/effective-dart/usage.md
Labels: EffectiveDart, Examples, Tests, cla: yes

#1049 Reinstate DartPad example now that it uses SDK 2-dev.69.5
  src/_guides/language/sound-dart.md
  src/tools/dartpad.md
  src/tools/pub/cmd/pub-run.md
Labels: Dart2, cla: yes

#1050 Fix a number of "Effective Dart" issues.
  examples/misc/lib/effective_dart/docs_bad.dart
  examples/misc/lib/effective_dart/docs_good.dart
  examples/misc/lib/effective_dart/style_good.dart
  examples/misc/test/effective_dart_test.dart
  src/_guides/language/effective-dart/documentation.md
  src/_guides/language/effective-dart/style.md
  src/_guides/language/effective-dart/usage.md
Labels: cla: yes

#1045 Dart 2 async note tweaks
  src/_articles/language/await-async.md
  src/_assets/stylesheets/main.scss
  src/_includes/async-await-2.0.html
  src/_includes/async-await-2.0.md
  src/_tutorials/language/futures.md
Labels: Dart2, cla: yes

#1052 fix: language-tour.md spelling mistake
  src/_guides/language/language-tour.md
Labels: cla: yes

#1054 Update some old dartdoc.org references
  src/_guides/libraries/create-library-packages.md
Labels: cla: yes

#1055 Update "Distributing a library"
  src/_guides/libraries/create-library-packages.md
Labels: cla: yes

#1056 Tweak banner, add link to announcement.
  src/_includes/banner.html
Labels: cla: yes

#1060 Examples: drop remaining unnecessary const
  examples/httpserver/bin/number_guesser.dart
  examples/misc/lib/tutorial/cat_no_hash.dart
  examples/misc/test/library_tour/core_test.dart
  examples/misc/test/samples_test.dart
  examples/strong/test/strong_test.dart
  src/_guides/libraries/library-tour.md
  src/_tutorials/language/streams.md
Labels: cla: yes

#1063 Remove (beta) suffix from Dart 2.0 in version menu
  src/_includes/_version-menu-items.html
Labels: cla: yes

#1062 Added entry to who uses dart
  src/community/who-uses-dart.md
Labels: cla: yes

#1067 Major cleanup of redirect rules
  firebase.json
  src/_tutorials/dart-vm/httpserver.md
Labels: Infrastructure, cla: yes

#1074 Recommend SDK lower constraint of 2.0.0.
  src/tools/pub/pubspec.md
Labels: cla: yes

#1076 Followup to redirect rule cleanup
  firebase.json
Labels: Infrastructure, cla: yes

#1080 Add back the whereType note, for now.
  src/_guides/language/effective-dart/usage.md
Labels: cla: yes

#1087 Clarify SDK constraint recommendations
  src/tools/pub/pubspec.md
Labels: cla: yes

#1089 Reinstate link checking
  .gitignore
  .travis.yml
  firebase.json
  scripts/before-install.sh
Labels: Infrastructure, cla: yes

#1092 FAQ front matter tweaks
  src/faq.md
Labels: cla: yes

#1084 Update paragraph about constraints
  .gitignore
  src/dart-2.md
Labels: cla: yes

#1097 chore: drop old unused images
  src/_assets/page_assets/covers/the-dart-programming-language.jpg
  src/_assets/page_assets/covers/what-is-dart.png
  src/_assets/page_assets/dart-tips/class-hierarchy.png
  src/_assets/page_assets/dart-tips/ep-5-flowchart.png
  src/_assets/page_assets/dart-tips/ep-5-hierarchy.png
  src/_assets/page_assets/dart-tips/marakana-logo.png
  src/_assets/page_assets/tools/dart-editor.png
  src/_assets/page_assets/tools/dart-logo-48.png
  src/_assets/page_assets/tools/dartium-logo-48.jpg
  src/_assets/page_assets/tools/dump-info-viewer.png
  src/_assets/page_assets/tools/eclipse.png
  src/_assets/page_assets/tools/input-and-output-assets.png
  src/_assets/page_assets/tools/sublime.png
  src/_assets/page_assets/tools/webstorm.svg
Labels: Infrastructure, cla: yes

#1112 Add alt text to images that don't already have it
  src/_articles/libraries/converters-and-codecs.md
  src/_guides/language/analysis-options.md
  src/_guides/language/language-tour.md
  src/_guides/libraries/create-library-packages.md
  src/_guides/platforms.md
  src/_tutorials/dart-vm/get-started.md
  src/_tutorials/language/futures.md
  src/_tutorials/language/streams.md
  src/install.md
  src/tools/pub/versioning.md
Labels: cla: yes
