Repository dart-lang/site-www, pull requests merged in 2019-10, with the labels that each got.

#1967 Add missing example in add-elements
  src/_tutorials/web/low-level-html/add-elements.md
Labels: cla: yes

#1971 Fix #1970
  src/_tutorials/web/fetch-data.md
Labels: cla: yes

#1974 Slightly subdue the analyzer error formatting
  src/_guides/language/analysis-options.md
Labels: cla: yes

#1781 list bullet changing without animation
  src/_assets/css/_dash.scss
  src/assets/dash/2x/bullet-black.png
  src/index.html
Labels: cla: yes

#1979 Fix issue in shared-pkgs tutorial
  src/_tutorials/libraries/shared-pkgs.md
Labels: cla: yes

#1982 Update Debian install instructions to use wget
  src/tools/sdk/_linux.md
Labels: cla: yes

#1983 Change dart convert link
  src/_tutorials/server/cmdline.md
Labels: cla: yes

#1985 Clarify wording around pubspec
  src/_guides/packages.md
Labels: cla: yes

#1980 Patch #1966
  src/_tutorials/web/low-level-html/connect-dart-html.md
Labels: cla: yes

#1984 Update pub.dev site name
  src/_articles/archive/zones.md
  src/_articles/libraries/dart-io.md
  src/_guides/libraries/create-library-packages.md
  src/_guides/libraries/library-tour.md
  src/_guides/libraries/useful-libraries.md
  src/_guides/packages.md
  src/_tutorials/index.md
  src/_tutorials/libraries/index.md
  src/_tutorials/libraries/shared-pkgs.md
  src/faq.md
  src/server/libraries.md
  src/tools/pub/cmd/index.md
  src/tools/pub/cmd/pub-get.md
  src/tools/pub/cmd/pub-global.md
  src/tools/pub/cmd/pub-lish.md
  src/tools/pub/cmd/pub-uploader.md
  src/tools/pub/dependencies.md
  src/tools/pub/environment-variables.md
  src/tools/pub/glossary.md
  src/tools/pub/index.md
  src/tools/pub/package-layout.md
  src/tools/pub/publishing.md
  src/tools/pub/pubspec.md
  src/web/js-interop.md
Labels: cla: yes

#1987 Fix homepage layout on very wide screens
  src/_assets/css/README.md
  src/_assets/css/_dash.scss
  src/index.html
Labels: cla: yes

#1988 Remove extra apostrophe
  src/_guides/language/effective-dart/design.md
Labels: cla: yes

#1964 Update analysis-options.md with info about using 2 YAML formats
  src/_guides/language/analysis-options.md
Labels: cla: yes

#1986 Verified publishers docs
  src/_assets/image/verified-publisher.svg
  src/_data/side-nav.yml
  src/tools/pub/publishing.md
  src/tools/pub/verified-publishers.md
Labels: cla: yes

#1991 Add paragraph for discontinuing packages
  src/tools/pub/publishing.md
Labels: cla: yes

#1989 Add missing command line parameter
  src/_tutorials/server/cmdline.md
Labels: cla: yes

#1992 Update banner.html
  src/_includes/banner.html
Labels: cla: yes

#1993 Create dart2native.md
  src/tools/dart2native.md
Labels: cla: yes

#1995 Update testing.md
  src/_guides/testing.md
Labels: cla: yes, needs-info

#1998 examples/README.md: clarify steps to run analyzer
  examples/README.md
Labels: cla: yes, docs, examples

#2001 DartPad troubleshooting: mention GitHub rate limiting
  src/_tutorials/web/low-level-html/add-elements.md
  src/tools/dartpad/troubleshoot.md
Labels: cla: yes

#2004 Markdown cleanup: no need for spaces in Jekyll directives
  src/_guides/language/language-tour.md
  src/_guides/libraries/c-interop.md
  src/_tutorials/language/streams.md
  src/_tutorials/server/get-started.md
  src/_tutorials/web/fetch-data.md
  src/_tutorials/web/get-started.md
  src/_tutorials/web/low-level-html/add-elements.md
  src/_tutorials/web/low-level-html/remove-elements.md
  src/codelabs/async-await/index.md
  src/codelabs/dart-cheatsheet/index.md
  src/tools/dartpad/index.md
  src/tools/pub/publishing.md
Labels: cla: yes, cleanup/refactoring

#2000 Update code color
  src/_assets/css/_variables.scss
  src/_assets/css/main.scss
Labels: cla: yes, design

#2003 CI: support analyzer-results varying by Dart channel
  examples/README.md
  examples/analysis/analyzer-results-dev.txt
  examples/analysis/analyzer-results-stable.txt
  examples/analysis/lib/assignment.dart
  examples/analysis/lib/lint.dart
  examples/misc/analyzer-1-results.txt
  examples/misc/analyzer-results-dev.txt
  examples/misc/analyzer-results-stable.txt
  examples/misc/lib/language_tour/generics/misc.dart
  examples/misc/lib/library_tour/core/collections.dart
  examples/misc/lib/library_tour/core/hash_code.dart
  examples/strong/analyzer-1-results.txt
  examples/strong/analyzer-results-dev.txt
  examples/strong/analyzer-results-stable.txt
  examples/strong/lib/animal_bad.dart
  examples/strong/lib/bounded/instantiate_to_bound.dart
  examples/strong/lib/common_fixes_analysis.dart
  examples/strong/lib/common_problems_analysis.dart
  examples/strong/lib/strong_analysis.dart
  examples/strong/test/strong_test.dart
  src/_guides/language/analysis-options.md
  src/_guides/language/sound-dart.md
  src/_guides/language/sound-problems.md
  src/_guides/libraries/library-tour.md
  tool/analyze-and-test-examples.sh
Labels: cla: yes, examples, infrastructure

#2006 pub/troubleshooting: fix link
  src/tools/pub/troubleshoot.md
Labels: bad URL, cla: yes

#2005 Fix invalid anchor in publishing page
  src/tools/pub/publishing.md
Labels: bad URL, cla: yes, cleanup/refactoring

#2017 CI: deploy site only once per build
  .travis.yml
  tool/build-and-check-links.sh
  tool/build.sh
Labels: cla: yes, infrastructure

#2021 change address of example links
  src/_tutorials/server/httpserver.md
Labels: cla: yes

#2025 [ADD] - hint link for webdev docs
  src/_tutorials/server/httpserver.md
Labels: cla: yes

#2026 Recover CSS prettify-filename style
  src/_assets/css/main.scss
Labels: cla: yes, design

#2028 Delete some images that are no longer used
  src/_articles/archive/images/event-loop-and-main.png
  src/_articles/archive/images/event-loop-example.png
  src/_articles/archive/images/event-loop.png
  src/diagrams/articles/event-loop/event-loop.graffle/data.plist
  src/diagrams/articles/event-loop/event-loop.graffle/image4.tiff
Labels: cla: yes

#2031 docs: fix typo
  src/_guides/language/language-tour.md
Labels: cla: yes

#2034 docs: fix typo
  src/_guides/language/effective-dart/design.md
Labels: cla: yes

#2033 docs: fix typo
  src/_guides/language/language-tour.md
Labels: cla: yes

#2036 Fixed the Grammatical errors.
  CONTRIBUTING.md
  README.md
Labels: cla: yes

#2037 Style: fix positioning of static analysis code block labels
  src/_assets/css/main.scss
Labels: cla: yes, design

#2038 Reclaim 'good' and 'bad' style names
  src/_articles/libraries/creating-streams.md
  src/_assets/css/main.scss
  src/_guides/language/effective-dart/design.md
  src/_guides/language/effective-dart/documentation.md
  src/_guides/language/effective-dart/style.md
  src/_guides/language/effective-dart/usage.md
Labels: cla: yes, cleanup/refactoring, design

#2051 Fix page-source links for pages migrated from site-shared
  _config.yml
Labels: cla: yes
