Repository dart-lang/site-www, pull requests merged in 2019-11, with the labels that each got.

#2058 Upgrade to Node 12, firebase-tools 7.6
  package.json
  tool/before-install.sh
  tool/env-set.sh
Labels: cla: yes, infrastructure

#2062 Books page: fix ToC links, drop image external-link icon, make page mobile friendly
  src/_assets/css/_books.scss
  src/_assets/css/_bootstrap_config.scss
  src/resources/books.md
Labels: cla: yes

#2048 dart2native & dartaotruntime docs
  firebase.json
  src/_data/side-nav.yml
  src/_tutorials/server/get-started.md
  src/faq.md
  src/platforms.md
  src/tools/dart2aot.md
  src/tools/dart2native.md
  src/tools/dartaotruntime.md
  src/tools/index.md
  src/tools/sdk/index.md
Labels: blocked, cla: yes

#2052 dart:ffi beta
  src/_guides/libraries/c-interop.md
Labels: blocked, cla: yes

#1990 Update landing page native visualization
  src/assets/dash/1x/3-1 - aot compile-80.jpg
  src/assets/dash/2x/3-1 - aot compile@2x-80.jpg
Labels: blocked, cla: yes

#2065 Adjust expected analyzer results now that 2.6.0 is out
  examples/analysis/analyzer-results-stable.txt
  examples/analysis/analyzer-results.txt
  examples/misc/analyzer-results-stable.txt
  examples/misc/analyzer-results.txt
  examples/strong/analyzer-results-stable.txt
  examples/strong/analyzer-results.txt
  src/_data/pkg-vers.json
  src/_guides/language/analysis-options.md
  src/_guides/language/sound-dart.md
  src/_guides/language/sound-problems.md
Labels: cla: yes, examples, tests

#2049 fixed a typo
  README.md
Labels: cla: yes

#2066 2.6 banner
  src/_includes/banner.html
Labels: cla: yes

#2067 ffi beta
  src/_guides/libraries/c-interop.md
Labels: cla: yes

#2073 Use HTTPS in links when possible
  src/_articles/archive/numeric-computation.md
  src/_articles/libraries/dart-io.md
  src/_guides/language/analysis-options.md
  src/_guides/language/effective-dart/documentation.md
  src/_guides/language/effective-dart/style.md
  src/_guides/language/language-tour.md
  src/_guides/language/spec.md
  src/_guides/libraries/dart-html-tour.md
  src/_includes/get-sdk.md
  src/_tutorials/server/httpserver.md
  src/_tutorials/web/get-started.md
  src/community/index.md
  src/faq.md
  src/get-dart.md
  src/security.md
  src/tools/dart2js.md
  src/tools/dartpad/privacy.md
  src/tools/pub/dependencies.md
  src/tools/pub/glossary.md
  src/tools/pub/package-layout.md
  src/tools/pub/publishing.md
  src/tools/pub/pubspec.md
  src/tools/sdk/_mac.md
  src/tools/sdk/dart_sdk_archive/README.md
  src/tools/sdk/index.md
  src/web/deployment.md
Labels: cla: yes

#2076 Fix build and improve a URL
  examples/misc/lib/effective_dart/docs_good.dart
  src/tools/sdk/_windows.md
Labels: cla: yes

#2070 Add known limitations, mention dart2aot
  src/tools/dart2native.md
Labels: cla: yes

#2078 Move dart2aot info down the page
  src/tools/dart2native.md
Labels: cla: yes

#2081 Fix linux get-sdk links
  src/tools/sdk/_linux.md
  src/tools/sdk/archive/assets/install.js
Labels: cla: yes, cleanup/refactoring, infrastructure

#2082 Upgrade to jquery 3.4.1
  src/_assets/js/main.js
  src/_assets/js/vendor/jquery-3.4.1.js
Labels: cla: yes, infrastructure

#2087 Clarify that you need bash to build the site
  README.md
Labels: cla: yes

#2079 Document conditional imports
  examples/create_libraries/dart_test.yaml
  examples/create_libraries/example/hw_example.dart
  examples/create_libraries/lib/hw_mp.dart
  examples/create_libraries/lib/src/hw_html.dart
  examples/create_libraries/lib/src/hw_io.dart
  examples/create_libraries/lib/src/hw_none.dart
  examples/create_libraries/pubspec.yaml
  examples/create_libraries/test/hw_mp_browser_test.dart
  examples/create_libraries/test/hw_mp_test.dart
  src/_guides/language/language-tour.md
  src/_guides/libraries/create-library-packages.md
Labels: cla: yes

#2089 Cheatsheet: fix code comment
  src/codelabs/dart-cheatsheet/index.md
Labels: cla: yes

#2032 Add DartPad best practices page
  src/codelabs/async-await/index.md
  src/resources/dartpad-tutorials.pdf
  src/tools/dartpad/index.md
  src/tools/dartpad/troubleshoot.md
Labels: cla: yes

#2092 Server > Get Started: use tested sources for DartPad Hello World
  src/_assets/css/_overwrites.scss
  src/_assets/css/main.scss
  src/_tutorials/server/get-started.md
Labels: cla: yes, examples, tests

#2094 Server > Get Started: fix front matter
  src/_tutorials/server/get-started.md
  tool/build.sh
Labels: cla: yes

#2096 Fail build on bad front-matter YAML
  _config.yml
Labels: cla: yes, infrastructure

#2097 Make DartPad resizable in Tutorial > Server > Get started
  src/_tutorials/server/get-started.md
Labels: cla: yes, design

#2099 Update pub-deps.md
  src/tools/pub/cmd/pub-deps.md
Labels: cla: yes

#2098 Add perf Q&A to faq.md
  src/faq.md
Labels: cla: yes

#2100 Add await to the operator precedence table
  src/_guides/language/language-tour.md
Labels: cla: yes

#2105 Update firebase-tools to 7.7
  package.json
Labels: cla: yes, infrastructure

#2104 Markdown cleanup: use code fences in prep for DartPad updates
  _config.yml
  src/_assets/css/_code.scss
  src/_guides/language/language-tour.md
  src/_guides/language/sound-problems.md
  src/_guides/libraries/_dart-html-tour.md
  src/_guides/libraries/library-tour.md
  src/_includes/async-await-2.0.md
  src/_tutorials/language/streams.md
  src/_tutorials/web/fetch-data.md
  src/_tutorials/web/get-started.md
  src/codelabs/async-await.md
  src/codelabs/dart-cheatsheet.md
Labels: cla: yes, cleanup/refactoring

#2109 Update code refresh scripts, bring over flutter-site improvements
  tool/check-code.sh
  tool/refresh-code-excerpts.sh
Labels: cla: yes, infrastructure

#2111 Fix note_client.dart bug; add missing server tests; test cleanup
  examples/README.md
  examples/create_libraries/README.md
  examples/create_libraries/dart_test.yaml
  examples/create_libraries/example/hw_example.dart
  examples/create_libraries/pubspec.yaml
  examples/create_libraries/test/hw_mp_browser_test.dart
  examples/create_libraries/test/hw_mp_test.dart
  examples/dart_test_base.yaml
  examples/dart_test_base_browser.yaml
  examples/html/README.md
  examples/html/dart_test.yaml
  examples/html/lib/html.dart
  examples/html/pubspec.yaml
  examples/html/web/favicon.png
  examples/httpserver/README.md
  examples/httpserver/bin/basic_file_server.dart
  examples/httpserver/bin/index.html
  examples/httpserver/bin/mini_file_server.dart
  examples/httpserver/bin/note_server.dart
  examples/httpserver/bin/static_file_server.dart
  examples/httpserver/dart_test.yaml
  examples/httpserver/data/notes.txt
  examples/httpserver/test/httpserver_test.dart
  examples/httpserver/web/favicon.ico
  examples/httpserver/web/index.html
  examples/httpserver/web/note_client.dart
  examples/httpserver/web/note_taker.html
  examples/httpserver/web/styles.css
  examples/misc/dart_test.yaml
  examples/strong/dart_test.yaml
  src/_guides/libraries/create-library-packages.md
  src/_tutorials/server/httpserver.md
Labels: cla: yes, examples, infrastructure, tests

#2112 Recover and update examples/fetch_data
  examples/fetch_data/analysis_options.yaml
  examples/fetch_data/dart_test.yaml
  examples/fetch_data/pubspec.yaml
  examples/fetch_data/web/favicon.png
  examples/fetch_data/web/index.html
  examples/fetch_data/web/main.dart
  examples/fetch_data/web/portmanteaux.json
  examples/fetch_data/web/portmanteaux/index.html
  examples/fetch_data/web/portmanteaux/main.dart
  examples/fetch_data/web/portmanteaux/styles.css
  examples/fetch_data/web/portmanteaux2/index.html
  examples/fetch_data/web/portmanteaux2/main.dart
  examples/fetch_data/web/portmanteaux2/styles.css
  examples/fetch_data/web/styles.css
  src/_tutorials/web/fetch-data.md
  tool/analyze-and-test-examples.sh
Labels: cla: yes, examples

#2085 Updates related to verified publishers, author/authors
  src/tools/pub/cmd/pub-uploader.md
  src/tools/pub/glossary.md
  src/tools/pub/publishing.md
  src/tools/pub/pubspec.md
  src/tools/pub/troubleshoot.md
Labels: cla: yes

#2101 Add directions for getting the args package
  src/_tutorials/server/cmdline.md
Labels: cla: yes

#2115 Add video element to page
  src/_assets/css/_dash.scss
  src/_assets/js/main.js
  src/assets/dash/js/dartpad_picker_main.dart.js
  src/index.html
  tool/dartpad_picker/compile_dev.sh
  tool/dartpad_picker/lib/dartpad_picker.dart
Labels: cla: yes

#2120 Cleanup linkcheck-skip-list.txt localhost rules
  tool/config/linkcheck-skip-list.txt
Labels: cla: yes, cleanup/refactoring, infrastructure

#2123 Dartpad_picker/compile scripts: don't wipe out entire tmp dir
  tool/dartpad_picker/compile.sh
  tool/dartpad_picker/compile_dev.sh
Labels: cla: yes, infrastructure

#2122 Cleanup corelib page
  src/_guides/libraries/index.md
Labels: cla: yes

#2125 Fix linkcheck-skip-list.txt localhost rule
  tool/config/linkcheck-skip-list.txt
Labels: cla: yes, infrastructure

#1846 Advise UpperCamelCase extensions
  examples/misc/lib/effective_dart/style_good.dart
  src/_guides/language/effective-dart/style.md
  src/_guides/language/effective-dart/toc.md
Labels: blocked, cla: yes, ⚠ WIP

#2131 Delete obsolete note about Dart fork of Chrome DevTools
  src/web/debugging.md
Labels: cla: yes

#2124 Ensure Try-Dart example sources are analyzed and tested
  examples/misc/bin/try_dart/classes.dart
  examples/misc/bin/try_dart/collection_literals.dart
  examples/misc/bin/try_dart/control_flow.dart
  examples/misc/bin/try_dart/functions.dart
  examples/misc/bin/try_dart/strings.dart
  examples/misc/lib/pi_monte_carlo.dart
  examples/misc/pubspec.yaml
  examples/misc/test/try_dart_test.dart
  src/_try-dart-examples.md
  src/assets/dash/js/dartpad_picker_main.dart.js
  src/index.html
  tool/dartpad_picker/compile.sh
  tool/dartpad_picker/compile_dev.sh
  tool/dartpad_picker/lib/dartpad_picker.dart
  tool/dartpad_picker/web/dartpad_picker_main.dart
Labels: DartPad, cla: yes, examples, tests

#2136 Update diagnostic-messages.md
  src/tools/diagnostic-messages.md
Labels: cla: yes

#2134 Fix cases of method named with get
  examples/httpserver/bin/note_server.dart
  examples/httpserver/test/httpserver_test.dart
  examples/misc/lib/language_tour/classes/employee.dart
  examples/strong/test/strong_test.dart
  src/_guides/language/language-tour.md
  src/_guides/language/sound-problems.md
  src/tools/sdk/dart_sdk_archive/lib/src/generator.dart
  src/tools/sdk/dart_sdk_archive/lib/src/util.dart
  src/tools/sdk/dart_sdk_archive/lib/src/version_selector.dart
  src/tools/sdk/dart_sdk_archive/test/svn_revisions_test.dart
  src/tools/sdk/dart_sdk_archive/tool/grind.dart
  src/tools/sdk/sdk_builds.dart/example/print_latest_versions.dart
  src/tools/sdk/sdk_builds.dart/lib/src/dart_downloads.dart
  src/tools/sdk/sdk_builds.dart/test/sdk_builds_test.dart
  tool/create_code_with_tooltips.dart
  tool/dartpad_picker/web/dartpad_picker_main.dart
Labels: cla: yes

#2137 Closes #2128 : Change get* function names to fetch* function names.
  src/codelabs/async-await.md
Labels: cla: yes

#2141 Closes #2128 Reinstate `createOrderMessage()` in cases lacking print statements
  src/codelabs/async-await.md
Labels: cla: yes
