Repository dart-lang/site-www, pull requests merged in 2019-09, with the labels that each got.

#1861 fix a top-5 404
  firebase.json
Labels: cla: yes

#1862 Minor grammar fix: Adding a missing word
  src/_guides/language/analysis-options.md
Labels: cla: yes

#1864 Fix formatting of a warning
  src/_guides/language/analysis-options.md
Labels: cla: yes

#1867 Remove the 2.4 announcement banner
  _config.yml
Labels: cla: yes

#1866 Update pub get troubleshoot documentation
  src/tools/pub/troubleshoot.md
Labels: cla: yes

#1875 Remove src/_includes/dartpad.html, which is no longer used.
  src/_includes/dartpad.html
Labels: cla: yes

#1876 Add links to samples page & cheatsheet codelab
  src/_guides/language/language-tour.md
  src/samples/index.md
Labels: cla: yes

#1874 Update async-await codelab
  src/codelabs/async-await/index.md
Labels: cla: yes

#1849 dart:ffi docs
  firebase.json
  src/_data/side-nav.yml
  src/_guides/libraries/c-interop.md
  src/server/c-interop.md
Labels: cla: yes

#1870 [WIP] Add info about 2.5 const expansion
  examples/misc/lib/effective_dart/usage_bad.dart
  examples/misc/lib/language_tour/variables.dart
  examples/misc/pubspec.yaml
  examples/strong/analyzer-2-results.txt
  examples/strong/lib/animal_bad.dart
  examples/strong/lib/common_problems_analysis.dart
  examples/strong/lib/strong_analysis.dart
  src/_guides/language/language-tour.md
  src/_guides/language/sound-problems.md
Labels: cla: yes

#1883 Update banner.html for 2.5.0 release
  _config.yml
  src/_includes/banner.html
Labels: cla: yes

#1881 Add dart:ffi status note
  src/_guides/libraries/c-interop.md
Labels: cla: yes

#1882 Fix title of dart:ffi page
  src/_guides/libraries/c-interop.md
Labels: cla: yes

#1885 Update security.md
  src/security.md
Labels: cla: yes

#1873 Add isolate example to the language tour
  src/_guides/language/language-tour.md
Labels: cla: yes

#1888 cmdline: Hello World example cleanup and test
  src/_tutorials/server/cmdline.md
Labels: cla: yes

#1890 Update DartPad troubleshooting page
  src/tools/dartpad/troubleshoot.md
Labels: cla: yes

#1893 Fix analyze-and-test-examples.sh array var append
  tool/analyze-and-test-examples.sh
Labels: cla: yes, infrastructure

#1898 Update vers to 2.5
  src/_data/pkg-vers.json
Labels: cla: yes

#1900 tool/create_site_main_example.dart: rework to support multiple files
  examples/misc/lib/pi_monte_carlo.dart
  src/_main-example.html
  tool/create_site_main_example.dart
Labels: cla: yes, infrastructure

#1901 Tool rename
  examples/misc/lib/pi_monte_carlo.dart
  src/_main-example.html
  tool/create_code_with_tooltips.dart
Labels: cla: yes, infrastructure

#1904 _config.yml: add a generic warning alert w/o a label
  _config.yml
Labels: cla: yes

#1905 tool/analyze-and-test-examples.sh: analyze options file too
  examples/misc/analyzer-2-results.txt
  examples/strong/analyzer-2-results.txt
  tool/analyze-and-test-examples.sh
Labels: Tests, cla: yes, examples, infrastructure

#1908 Code excerpts: distribute site-global replace pattern to individual files
  src/_guides/language/language-tour.md
  src/_guides/language/sound-dart.md
  src/_guides/language/sound-problems.md
  src/_guides/libraries/library-tour.md
  tool/refresh-code-excerpts.sh
Labels: cla: yes, infrastructure

#1909 Examples: misc pubspec updates
  examples/misc/pubspec.yaml
  examples/strong/pubspec.yaml
  examples/util/pubspec.yaml
Labels: cla: yes, examples

#1910 Add Firebase project aliases for new staging servers
  .firebaserc
Labels: cla: yes, infrastructure

#1911 Upgrade firebase-tools
  package.json
Labels: cla: yes, infrastructure

#1914 Move dartpad_picker tool from site src into tool folder
  src/_packages/dartpad_picker/README.md
  src/_packages/dartpad_picker/compile.sh
  src/assets/dash/js/dartpad_picker_main.dart.js
  tool/dartpad_picker/.gitignore
  tool/dartpad_picker/README.md
  tool/dartpad_picker/analysis_options.yaml
  tool/dartpad_picker/compile.sh
  tool/dartpad_picker/lib/dartpad_picker.dart
  tool/dartpad_picker/pubspec.yaml
  tool/dartpad_picker/web/dartpad_picker_main.dart
Labels: cla: yes, infrastructure

#1917 Add fallback image to main page video(dart-lang#1889)
  src/index.html
Labels: cla: yes

#1897 Update search.html
  src/search.html
Labels: cla: yes

#1896 Update search-all.html
  src/search-all.html
Labels: cla: yes

#1902 Analyze/test cmdline tutorial code excerpts
  examples/misc/analyzer-2-results.txt
  examples/misc/bin/dcat.dart
  examples/misc/bin/dcat1.dart
  examples/misc/bin/dcat_tooltips.html
  examples/misc/lib/tutorial/cmdline.dart
  examples/misc/pubspec.yaml
  src/_tutorials/server/_dcat-example.html
  src/_tutorials/server/cmdline.md
  src/_tutorials/server/images/commandlineargs.png
  src/diagrams/tutorials/cmdline/commandlineargs.graffle
  tool/create_code_with_tooltips.dart
  tool/dartfmt.sh
  tool/pubspec.yaml
Labels: Tests, Tutorials, cla: yes, examples

#1923 removed retype() method from Stream class
  src/_tutorials/language/streams.md
Labels: cla: yes

#1925 Fix the build
  examples/misc/lib/tutorial/stream_interface.dart
Labels: cla: yes

#1933 Drop reference to Jekyll conf var that doesn't exist
  src/_includes/dart-html-tour.md
  src/get-dart.md
  src/tools/sdk/index.md
Labels: cla: yes, cleanup/refactoring

#1921 Get-started server tutorial: analyze/test code excerpts
  examples/misc/test/tutorial/get_started.dart
  src/_includes/get-sdk.md
  src/_tutorials/libraries/shared-pkgs.md
  src/_tutorials/server/get-started.md
  src/_tutorials/web/get-started.md
  src/get-dart.md
  src/tools/pub/cmd/pub-global.md
  src/tools/pub/troubleshoot.md
  src/tools/sdk/_linux.md
  src/tools/sdk/_mac.md
  src/web/debugging.md
Labels: Tests, cla: yes, design, examples, infrastructure

#1936 Rename dartlang.org and variants to dart.dev
  README.md
  examples/analysis/lib/assignment.dart
  examples/analysis/pubspec.yaml
  examples/httpserver/pubspec.yaml
  examples/misc/lib/effective_dart/design_bad.dart
  examples/misc/lib/effective_dart/design_good.dart
  examples/misc/lib/effective_dart/docs_bad.dart
  examples/misc/lib/effective_dart/docs_good.dart
  examples/misc/lib/tutorial/daily_news.dart
  examples/misc/pubspec.yaml
  examples/misc/test/language_tour/basic_test.dart
  examples/misc/test/language_tour/classes_test.dart
  examples/misc/test/language_tour/control_flow_test.dart
  examples/misc/test/language_tour/functions_test.dart
  examples/misc/test/language_tour/operators_test.dart
  examples/misc/test/library_tour/core_test.dart
  examples/misc/test/library_tour/io_test.dart
  examples/misc/test/library_tour/math_test.dart
  examples/misc/test/samples_test.dart
  examples/misc/test/tutorial/futures_test.dart
  examples/strong/lib/animal.dart
  examples/strong/lib/animal_bad.dart
  examples/strong/pubspec.yaml
  examples/strong/test/strong_test.dart
  examples/util/pubspec.yaml
  src/_guides/libraries/library-tour.md
  src/_includes/dart-html-tour.md
  src/_tutorials/web/fetch-data.md
  src/codelabs/async-await/index.md
  src/faq.md
  src/terms.md
  src/tools/pub/pubspec.md
  src/web/index.md
Labels: cla: yes, cleanup/refactoring

#1939 Use https in redirect rules
  firebase.json
Labels: cla: yes, cleanup/refactoring, infrastructure

#1940 Examples: drop unnecessary `const`
  examples/misc/test/language_tour/browser_test.dart
  examples/misc/test/pi_test.dart
Labels: Tests, cla: yes, cleanup/refactoring

#1938 Drop comment containing obsolete URL to API reference
  src/codelabs/async-await/index.md
Labels: cla: yes, cleanup/refactoring

#1941 Followup to #1940, drop unnecessary const
  examples/misc/test/language_tour/browser_test.dart
  examples/misc/test/pi_test.dart
Labels: cla: yes

#1886 Enable manual testing of the httpserver example
  examples/httpserver/pubspec.yaml
Labels: cla: yes

#1944 Close survey on futures codelab
  src/codelabs/async-await/index.md
Labels: cla: yes

#1945 Add a basic test for each of the three "cat" commands
  examples/misc/bin/cat_no_hash.dart
  examples/misc/test/bin_test.dart
  examples/misc/test_data/quote.txt
  src/_tutorials/language/streams.md
Labels: Tests, cla: yes, examples

#1950 Add support for Google Tags
  src/_includes/gtags.html
  src/_includes/head.html
  src/_layouts/default.html
  src/_layouts/error.html
  src/_layouts/homepage.html
Labels: cla: yes

#1951 Update diagnostic-messages.md
  src/tools/diagnostic-messages.md
Labels: cla: yes

#1952 Fix #1947
  src/_articles/libraries/creating-streams.md
Labels: cla: yes

#1954 Update FFI page to reflect new flutter.dev FFI page
  src/_guides/libraries/c-interop.md
  src/_includes/pub-in-prereleases.html
  src/dart-2.md
  src/get-dart.md
  src/tools/pub/publishing.md
  src/tools/pub/pubspec.md
  src/tools/sdk/archive/index.md
Labels: cla: yes

#1961 Move include file for dart:html tour
  src/_guides/libraries/dart-html-tour.md
  src/_guides/libraries/library-tour.md
Labels: cla: yes

#1956 Edit DartPad embeds, add troubleshooting instructions
  _config.yml
  src/_assets/css/main.scss
  src/_assets/image/dartpad-hello.png
  src/_guides/language/language-tour.md
  src/_includes/dartpad-embedded-troubleshooting.md
  src/_includes/dartpads-embedded-troubleshooting.md
  src/_tutorials/language/streams.md
  src/_tutorials/server/get-started.md
  src/_tutorials/web/fetch-data.md
  src/_tutorials/web/get-started.md
  src/_tutorials/web/low-level-html/add-elements.md
  src/_tutorials/web/low-level-html/connect-dart-html.md
  src/_tutorials/web/low-level-html/remove-elements.md
  src/assets/dash/js/dartpad_picker_main.dart.js
  src/codelabs/async-await/index.md
  src/codelabs/dart-cheatsheet/index.md
  src/tools/dartpad/index.md
  src/tools/dartpad/troubleshoot.md
  tool/dartpad_picker/lib/dartpad_picker.dart
Labels: cla: yes

#1963 Add missing ‘to’ in usage.md
  src/_guides/language/effective-dart/usage.md
Labels: cla: yes

#1957 Update web-tutorials.md
  src/_includes/web-tutorials.md
Labels: cla: yes
