Repository dart-lang/site-www, pull requests merged in 2021-12, with the labels that each got.

#3695 add userId example to DO capitalize acronyms
  src/_guides/language/effective-dart/style.md
Labels: cla: yes

#3666 Clarify when dependency overrides are used
  src/tools/pub/dependencies.md
Labels: cla: yes

#3409 Documenting `false_secrets` in `pubspec.yaml`
  firebase.json
  src/tools/pub/pubspec.md
Labels: tools, cla: yes, blocked

#3649 [Effective Dart] Update tear-off rule to mention constructor tear-offs.
  examples/misc/lib/effective_dart/usage_bad.dart
  examples/misc/lib/effective_dart/usage_good.dart
  examples/misc/pubspec.yaml
  src/_guides/language/effective-dart/usage.md
Labels: cla: yes, blocked

#3680 Add documentation on package retraction
  firebase.json
  src/tools/pub/publishing.md
Labels: cla: yes, blocked

#3694 Documentation on custom package repositories
  src/tools/pub/custom-package-repositories.md
  src/tools/pub/dependencies.md
  src/tools/pub/pubspec.md
Labels: cla: yes, blocked

#3693 Document `dart pub token`.
  src/_includes/pub-subcommands.md
  src/tools/pub/cmd/pub-token.md
  src/tools/pub/dependencies.md
Labels: cla: yes, blocked

#3696 New page: Concurrency in Dart
  diagrams/guides/concurrency/basics.svg
  diagrams/guides/concurrency/event-loop.svg
  diagrams/guides/concurrency/isolates.svg
  src/_guides/language/concurrency/images/basics-await.png
  src/_guides/language/concurrency/images/basics-isolate.png
  src/_guides/language/concurrency/images/basics-main-isolate.png
  src/_guides/language/concurrency/images/event-handling.png
  src/_guides/language/concurrency/images/event-jank.png
  src/_guides/language/concurrency/images/event-loop.png
  src/_guides/language/concurrency/images/isolate-api.png
  src/_guides/language/concurrency/images/isolate-bg-worker.png
  src/_guides/language/concurrency/images/isolate-custom-bg-worker.png
  src/_guides/language/concurrency/index.md
Labels: cla: yes, blocked

#3647 Describe new syntax for hosted dependencies
  src/tools/pub/dependencies.md
Labels: cla: yes
