Repository dart-lang/site-www, pull requests merged in 2022-10, with the labels that each got.

#4306 Update and standardize version of firebase-tools used to 11.15.0
  .github/workflows/build.yml
  Dockerfile
Labels: RFM

#4305 Adjust pub credential file locations
  src/tools/pub/troubleshoot.md
Labels: review:copy

#4302 Adjust anonymous function examples to not trigger lint
  examples/misc/test/language_tour/control_flow_test.dart
  examples/misc/test/language_tour/functions_test.dart
  src/_guides/language/language-tour.md
Labels: review:tech

#4310 Remove a few older version mentions
  src/_guides/language/extension-methods.md
  src/_guides/language/language-tour.md
  src/tools/pub/pubspec.md
Labels: review:copy

#4301 Expanding on the documentation for callable classes
  src/_guides/language/language-tour.md
Labels: review:tech

#4311 Some minor updates to JetBrains IDE page
  src/tools/jetbrains-plugin.md
Labels: review:copy

#4315 Add pub.dev to pub troubleshooting solution
  src/tools/pub/troubleshoot.md
Labels: review:tech

#4325 Document URI http and https factory constructors
  examples/misc/test/library_tour/core_test.dart
  src/_guides/libraries/library-tour.md
Labels: review:copy

#4326 Properly showcase a potentially useful await with non-void return type
  examples/misc/lib/effective_dart/usage_good.dart
  src/_guides/language/effective-dart/usage.md
Labels: review:any

#4330 Manually update ossf/scorecard-action to v2.0.6 to fix build
  .github/workflows/scorecards-analysis.yml
Labels: review:tech

#4328 Remove mention of initial lack of generic methods
  src/_guides/language/language-tour.md
Labels: review:copy
