Repository dart-lang/site-www, pull requests merged in 2023-06, with the labels that each got.

#4949 Update site for Dart 3.0.3 release
  Dockerfile
  src/_data/pkg-vers.json
Labels: RFM

#4940 Clarify list pattern snippet
  examples/language/lib/patterns/pattern_types.dart
  src/language/pattern-types.md
Labels: review:any

#4960 Fix some misc broken external links
  src/_guides/google-apis.md
  src/tools/pub/cmd/pub-token.md
  tool/config/linkcheck-skip-list.txt
Labels: review:copy

#4956 [New page] Class modifiers reference
  src/_data/side-nav.yml
  src/language/callable-objects.md
  src/language/class-modifiers.md
  src/language/enums.md
  src/language/mixins.md
  src/language/modifier-reference.md
Labels: review:tech

#4963 Remove unused styles and other cleanup
  src/_sass/README.md
  src/_sass/_books.scss
  src/_sass/_dartvm.scss
  src/_sass/_dash.scss
  src/_sass/_os-tabs.scss
  src/_sass/_overwrites.scss
  src/_sass/_site-overrides.scss
  src/_sass/components/_banner.scss
  src/_sass/components/_code.scss
  src/_sass/components/_cookie-notice.scss
  src/_sass/components/_form.scss
  src/_sass/components/_header.scss
  src/_sass/components/_search.scss
  src/_sass/components/_sidebar.scss
  src/_sass/components/_toc.scss
  src/_sass/core/_base.scss
  src/_sass/core/_bootstrap-config.scss
  src/_sass/core/_mixins.scss
  src/_sass/site.scss
Labels: RFM

#4961 Introduce a custom pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: RFM

#4954 "Library package" to just "package" or "regular package"
  firebase.json
  src/_data/side-nav.yml
  src/_guides/language/analysis-options.md
  src/_guides/language/coming-from/js-to-dart.md
  src/_guides/language/coming-from/swift-to-dart.md
  src/_guides/language/evolution.md
  src/_guides/libraries/create-packages.md
  src/_guides/libraries/private-files.md
  src/_guides/packages.md
  src/_tutorials/libraries/shared-pkgs.md
  src/language/keywords.md
  src/language/libraries.md
  src/tools/dart-doc.md
  src/tools/dart-run.md
  src/tools/linter-rules.md
  src/tools/pub/cmd/pub-get.md
  src/tools/pub/cmd/pub-outdated.md
  src/tools/pub/cmd/pub-upgrade.md
  src/tools/pub/dependencies.md
  src/tools/pub/glossary.md
  src/tools/pub/package-layout.md
Labels: RFM

#4978 fixed typo in 'Class modifiers for API maintainers' page
  src/language/class-modifiers-for-apis.md
Labels: cla: yes

#4981 Remove unused Jekyll and liquid plugins
  src/_plugins/inject_data_tag.rb
  src/_plugins/insert_tag.rb
  src/_plugins/nav_link_tag.rb
  src/_plugins/render.rb
  src/_plugins/svg_mime_type.rb
Labels: review:any

#4979 Fix incorrect class modifier highlighting in sidenav
  src/_data/side-nav.yml
Labels: review:any

#4980 Fix prev/next information for class modifier pages
  src/language/async.md
  src/language/class-modifiers-for-apis.md
Labels: review:copy

#4972 Adds I/O video on packages to publishing page
  src/tools/pub/publishing.md
Labels: RFM

#4986 Minor fixes and cleanup to branches page
  examples/language/lib/control_flow/branches.dart
  src/language/branches.md
Labels: review:copy

#4985 Link to new `use_string_in_part_of_directives` lint from Effective Dart
  src/effective-dart/usage.md
Labels: review:copy

#4975 No longer include prettify-css
  src/_includes/head.html
Labels: review:any

#4976 Add hover state to 'Try Dart' next step links
  src/_sass/_dash.scss
  src/_sass/components/_banner.scss
  src/_sass/core/_variables.scss
Labels: review:tech

#4990 Add a file listing all released, non-removed linter rules
  src/_includes/linter-rules-section.md
  src/tools/linter-rules/all.md
  src/tools/linter-rules/index.md
Labels: review:copy, review:tech

#4993 Update site to build with Dart 3.0.5
  Dockerfile
  src/_data/pkg-vers.json
Labels: review:any

#4973 Changed link on concurrency page
  src/language/concurrency/index.md
Labels: review:await-update

#4997 Update to Debian bookworm
  Dockerfile
Labels: review:tech

#5003 Add missing id-token configuration to code examples
  src/tools/pub/automated-publishing.md
Labels: review:tech

#5005 Fixed double negative
  examples/misc/lib/effective_dart/docs_good.dart
  src/effective-dart/documentation.md
Labels: review:copy

#5008 Rename `funcThatThrows` to `asyncErrorFunction`
  examples/futures/lib/early_error_handlers.dart
  examples/futures/lib/simple.dart
  examples/futures/lib/util.dart
  examples/futures/lib/when_complete.dart
  src/_guides/libraries/futures-error-handling.md
Labels: RFM

#5000 Add glossary redirect
  firebase.json
Labels: RFM

#5009 Update firebase-tools to v12.4.0
  .github/workflows/build.yml
  Dockerfile
Labels: RFM

#4974 Migrate from deprecated Sass `@import` to `@use` and `@forward`
  src/_sass/_books.scss
  src/_sass/_dartvm.scss
  src/_sass/_dash.scss
  src/_sass/_os-tabs.scss
  src/_sass/_overwrites.scss
  src/_sass/components/_banner.scss
  src/_sass/components/_code.scss
  src/_sass/components/_cookie-notice.scss
  src/_sass/components/_form.scss
  src/_sass/components/_header.scss
  src/_sass/components/_search.scss
  src/_sass/components/_sidebar.scss
  src/_sass/components/_toc.scss
  src/_sass/core/_base.scss
  src/_sass/core/_bootstrap-adjust.scss
  src/_sass/core/_bootstrap-config.scss
  src/_sass/core/_bootstrap.scss
  src/_sass/core/_mixins.scss
  src/_sass/core/_variables.scss
  src/_sass/site.scss
  src/_sass/vendor/_bootstrap.scss
  src/assets/css/main.scss
Labels: review:tech

#5006 Red underlines for diagnostics
  src/_sass/components/_code.scss
  src/tools/diagnostic-messages.md
Labels: review:copy

#4999 Implement individual linter rule pages
  firebase.json
  src/_data/linter_rules.json
  src/_includes/linter-page-content.md
  src/_includes/linter-rule-mention.md
  src/_includes/linter-rules-section.md
  src/_layouts/default.html
  src/_layouts/linter-rule-standalone.html
  src/_plugins/linter_page_generator.rb
  src/assets/img/tools/linter/has-fix.svg
  src/assets/img/tools/linter/style-core.svg
  src/assets/img/tools/linter/style-flutter.svg
  src/assets/img/tools/linter/style-recommended.svg
  src/effective-dart/style.md
  src/effective-dart/usage.md
  src/language/async.md
  src/resources/dart-3-migration.md
  src/tools/linter-rules/index.md
  src/tools/pub/package-layout.md
Labels: review:copy
