Repository dart-lang/site-www, pull requests merged in 2023-05, with the labels that each got.

#4795 Add some more relevant next steps in Try Dart
  src/index.html
Labels: RFM

#4797 Update for newest linter rules
  src/_data/linter_rules.json
Labels: RFM

#4799 Mention `dart pub add`
  src/_guides/packages.md
Labels: RFM

#4805 Add redirect for old broadcast streams article
  firebase.json
Labels: RFM

#4803 [Dart 3] Update build_runner examples
  examples/build_runner_usage/pubspec.yaml
  src/tools/build_runner.md
  src/tools/webdev.md
Labels: review:tech

#4754 [Dart 3] Class modifiers
  src/_data/side-nav.yml
  src/_guides/language/language-tour.md
  src/assets/js/language-tour-redirector.js
  src/language/class-modifiers.md
  src/language/classes.md
  src/language/index.md
  src/language/keywords.md
  src/language/methods.md
  src/language/mixins.md
Labels: RFM%

#4766 [Dart 3] Records
  src/_data/side-nav.yml
  src/_guides/libraries/library-tour.md
  src/language/built-in-types.md
  src/language/functions.md
  src/language/records.md
Labels: RFM%

#4780 [Dart 3] Patterns-related control flow
  firebase.json
  src/_articles/archive/dart-2.md
  src/_data/side-nav.yml
  src/_guides/language/coming-from/js-to-dart.md
  src/_guides/language/language-tour.md
  src/_guides/libraries/library-tour.md
  src/assets/js/language-tour-redirector.js
  src/language/branches.md
  src/language/collections.md
  src/language/concurrency/index.md
  src/language/control-flow.md
  src/language/enum.md
  src/language/error-handling.md
  src/language/functions.md
  src/language/index.md
  src/language/keywords.md
  src/language/loops.md
  src/language/operators.md
  src/language/variables.md
  src/tools/dart-run.md
Labels: RFM%

#4820 [Dart 3] Remove 'Dart 3 beta' mention from archive
  src/get-dart/archive/index.md
  src/null-safety/index.md
Labels: review:any

#4810 [Dart 3] Patterns
  src/_data/side-nav.yml
  src/language/pattern-types.md
  src/language/patterns.md
  src/resources/glossary.md
Labels: RFM%

#4824 [Dart 3] Cross links between new pages
  src/language/branches.md
  src/language/class-modifiers.md
  src/language/loops.md
  src/language/pattern-types.md
  src/language/patterns.md
  src/language/records.md
Labels: RFM%

#4823 [Dart 3] Adjustments for removed linter rules
  src/_data/linter_rules.json
  src/_includes/linter-rules-section.md
Labels: review:any

#4831 Update language repository links to use `main` branch
  firebase.json
  src/_articles/archive/dart-2.md
  src/_guides/language/analysis-options.md
  src/_guides/language/evolution.md
  src/_guides/language/spec.md
  src/language/collections.md
  src/language/extend.md
  src/language/extension-methods.md
  src/null-safety/migration-guide.md
  src/null-safety/understanding-null-safety/index.md
  src/null-safety/unsound-null-safety.md
  src/resources/faq.md
  src/resources/glossary.md
  src/tools/diagnostic-messages.md
Labels: review:any

#4808 [Dart 3] Migration guide
  src/_data/side-nav.yml
  src/null-safety/index.md
  src/resources/dart-3-migration.md
Labels: cla: no

#4857 Use code excerpts for /language/patterns page
  examples/language/lib/patterns/algebraic_datatypes.dart
  examples/language/lib/patterns/destructuring.dart
  examples/language/lib/patterns/for_in.dart
  examples/language/lib/patterns/json.dart
  examples/language/lib/patterns/switch.dart
  src/language/patterns.md
Labels: RFM

#4834 Expand on `mixin class`
  src/language/mixins.md
Labels: RFM%

#4877 Add `var` to Multiple returns in Records
  examples/language/test/records_test.dart
  src/language/records.md
Labels: review:tech

#4858 Excerpts for Class Modifiers
  examples/language/lib/class_modifiers/ex1/a.dart
  examples/language/lib/class_modifiers/ex1/b.dart
  examples/language/lib/class_modifiers/ex2/a.dart
  examples/language/lib/class_modifiers/ex2/b.dart
  examples/language/lib/class_modifiers/ex3/a.dart
  examples/language/lib/class_modifiers/ex3/b.dart
  examples/language/lib/class_modifiers/ex4/a.dart
  examples/language/lib/class_modifiers/ex4/b.dart
  examples/language/lib/class_modifiers/ex5/sealed.dart
  src/language/class-modifiers.md
Labels: RFM

#4853 Update site to build with Dart 3 stable instead of beta
  .github/workflows/build.yml
  Dockerfile
  Makefile
  examples/analysis/analyzer-results-stable.txt
  examples/analysis/pubspec.yaml
  examples/analysis_alt/pubspec.yaml
  examples/async_await/pubspec.yaml
  examples/build_runner_usage/pubspec.yaml
  examples/concurrency/pubspec.yaml
  examples/create_libraries/pubspec.yaml
  examples/extension_methods/pubspec.yaml
  examples/fetch_data/pubspec.yaml
  examples/futures/pubspec.yaml
  examples/html/pubspec.yaml
  examples/iterables/pubspec.yaml
  examples/language/pubspec.yaml
  examples/misc/pubspec.yaml
  examples/non_promotion/pubspec.yaml
  examples/null_safety_codelab/pubspec.yaml
  examples/type_system/pubspec.yaml
  examples/util/pubspec.yaml
  examples/vector_victor/pubspec.yaml
  pubspec.yaml
  src/_guides/language/analysis-options.md
Labels: review:tech

#4884 Clarify null safety migration SDK version step
  src/null-safety/migration-guide.md
Labels: review:any

#4885 Quick temporary Language Evolution entry for 3.0
  src/_guides/language/evolution.md
Labels: RFM

#4870 Add more detail to sealed definition
  src/language/class-modifiers.md
Labels: RFM

#4888 Fix linter rules release information
  src/_data/linter_rules.json
Labels: RFM%

#4887 Clarify switch expression usage
  src/language/branches.md
Labels: RFM%

#4894 Update site for release of Dart 3.0.1
  Dockerfile
  src/_data/pkg-vers.json
Labels: review:any

#4807 Add documentation for topics
  src/tools/pub/pubspec.md
Labels: review:copy

#4897 Move logical-or switch content to patterns page
  examples/language/lib/patterns/switch.dart
  src/language/branches.md
  src/language/pattern-types.md
  src/language/patterns.md
Labels: RFM%

#4879 Update list range error in patterns.md code excerpt
  examples/language/lib/patterns/json.dart
  src/language/patterns.md
Labels: review:tech

#4896 Remove links to 'Java to Dart' codelab
  src/codelabs/images/from-java-to-dart.png
  src/codelabs/index.md
  src/resources/faq.md
Labels: RFM

#4905 Update js-cookie from 3.0.1 to 3.0.5
  src/_includes/head.html
Labels: review:tech

#4859 Code excerpts for branches page
  examples/language/lib/control_flow/branches.dart
  src/language/branches.md
Labels: RFM

#4768 Clarify pub screenshot usage
  src/tools/pub/pubspec.md
Labels: RFM

#4909 Cleanup and standardize Effective Dart location and headers
  firebase.json
  src/_articles/index.md
  src/_data/docs_cards.yml
  src/_data/side-nav.yml
  src/_guides/language/analysis-options.md
  src/_guides/language/coming-from/js-to-dart.md
  src/_guides/language/coming-from/swift-to-dart.md
  src/_guides/language/effective-dart/toc.md
  src/_guides/language/evolution.md
  src/_guides/language/formatting.md
  src/_guides/language/index.md
  src/_guides/libraries/create-library-packages.md
  src/_guides/whats-new.md
  src/_tutorials/server/get-started.md
  src/_tutorials/web/get-started.md
  src/codelabs/async-await.md
  src/effective-dart/_readme.md
  src/effective-dart/design.md
  src/effective-dart/documentation.md
  src/effective-dart/index.md
  src/effective-dart/style.md
  src/effective-dart/toc.md
  src/effective-dart/usage.md
  src/language/classes.md
  src/language/comments.md
  src/language/constructors.md
  src/language/functions.md
  src/language/generics.md
  src/language/index.md
  src/language/libraries.md
  src/language/typedefs.md
  src/language/variables.md
  src/tools/dart-doc.md
  src/tools/dart-format.md
  src/tools/linter-rules.md
  src/tools/pub/package-layout.md
  tool/effective_dart_rules/analysis_options.yaml
  tool/effective_dart_rules/bin/main.dart
  tool/effective_dart_rules/pubspec.yaml
Labels: EffectiveDart, review:copy

#4868 Patterns types excerpts
  examples/language/lib/patterns/pattern_types.dart
  src/language/pattern-types.md
Labels: RFM

#4900 Add link reference checker tool
  pubspec.yaml
  src/_guides/language/coming-from/swift-to-dart.md
  src/_includes/tools/dart-compile-js-options.md
  src/tools/diagnostic-messages.md
  src/tools/webdev.md
  tool/check-links.sh
  tool/check_link_references.dart
Labels: review:copy, review:tech

#4882 The PUB_CACHE have moved.
  src/resources/dart-3-migration.md
Labels: RFM%

#4866 Fix TODOs for SCSS
  src/_sass/_books.scss
  src/_sass/_overwrites.scss
  src/_sass/components/_code.scss
  src/_sass/core/_base.scss
  src/_sass/core/_bootstrap-config.scss
  src/_sass/core/_variables.scss
  src/_sass/site.scss
Labels: RFM

#4895 Reorder pattern types by precedence
  examples/language/lib/patterns/pattern_types.dart
  src/language/pattern-types.md
Labels: review:copy

#4913 Fix Flutter compute link and mention
  src/language/concurrency/index.md
Labels: review:copy

#4917 Update linter rules for new rules and accurate Effective Dart links
  src/_data/linter_rules.json
Labels: review:copy

#4923 Update site to build with Dart 3.0.2
  Dockerfile
  src/_data/pkg-vers.json
Labels: review:copy, review:any

#4928 Fix 404 background
  src/_sass/components/_cookie-notice.scss
  src/_sass/site.scss
Labels: RFM

#4927 Make stage workflow not require test workflow
  .github/workflows/build.yml
  src/language/callable-objects.md
  src/language/class-modifiers.md
  src/language/methods.md
  src/language/mixins.md
Labels: review:any

#4934 Link to diagnostic messages instead of analyzer error code
  src/_guides/language/analysis-options.md
Labels: review:copy

#4926 Rename `/language/enum` page to `/language/enums`
  firebase.json
  src/_data/side-nav.yml
  src/_guides/language/coming-from/swift-to-dart.md
  src/_guides/language/evolution.md
  src/_guides/language/language-tour.md
  src/_guides/whats-new.md
  src/assets/js/language-tour-redirector.js
  src/language/branches.md
  src/language/enums.md
  src/language/index.md
  src/language/keywords.md
Labels: review:copy

#4925 Add previous and next links to language pages
  src/language/async.md
  src/language/branches.md
  src/language/built-in-types.md
  src/language/callable-objects.md
  src/language/class-modifiers.md
  src/language/classes.md
  src/language/collections.md
  src/language/comments.md
  src/language/concurrency/index.md
  src/language/constructors.md
  src/language/enums.md
  src/language/error-handling.md
  src/language/extend.md
  src/language/extension-methods.md
  src/language/functions.md
  src/language/generics.md
  src/language/index.md
  src/language/keywords.md
  src/language/libraries.md
  src/language/loops.md
  src/language/metadata.md
  src/language/methods.md
  src/language/mixins.md
  src/language/operators.md
  src/language/pattern-types.md
  src/language/patterns.md
  src/language/records.md
  src/language/type-system.md
  src/language/typedefs.md
  src/language/variables.md
Labels: language, RFM
