Repository dart-lang/site-www, pull requests merged in 2023-07, with the labels that each got.

#5028 Cleanup font configuration and fix some inconsistencies
  src/_sass/_dash.scss
  src/_sass/components/_banner.scss
  src/_sass/components/_sidebar.scss
  src/_sass/core/_base.scss
  src/_sass/core/_bootstrap.scss
  src/_sass/core/_colors.scss
  src/_sass/core/_variables.scss
  src/_sass/site.scss
Labels: review:any

#5044 Consistently use 'Google Sans' in sidenav
  src/_sass/components/_sidebar.scss
Labels: review:any

#5030 Improve analyzer page location
  firebase.json
  src/_articles/archive/dart-2.md
  src/_data/side-nav.yml
  src/_guides/language/coming-from/js-to-dart.md
  src/_guides/language/coming-from/swift-to-dart.md
  src/_guides/language/index.md
  src/_guides/language/sound-problems.md
  src/_guides/whats-new.md
  src/_includes/linter-page-content.md
  src/codelabs/async-await.md
  src/effective-dart/index.md
  src/effective-dart/style.md
  src/index.html
  src/language/type-system.md
  src/null-safety/migration-guide.md
  src/resources/dart-3-migration.md
  src/tools/analysis.md
  src/tools/dart-analyze.md
  src/tools/dart-fix.md
  src/tools/diagnostic-messages.md
  src/tools/experiment-flags.md
  src/tools/linter-rules/all.md
  src/tools/linter-rules/index.md
Labels: review:copy

#5023 Improve breadcrumbs style and enable for linter rules
  src/_layouts/default.html
  src/_plugins/linter_page_generator.rb
  src/_sass/core/_base.scss
  src/_sass/site.scss
  src/tools/linter-rules/all.md
  src/tools/linter-rules/index.md
Labels: review:copy

#5032 Remove out of date Dart 2 pages and guidance
  firebase.json
  src/_articles/archive/dart-2.md
  src/_guides/language/evolution.md
  src/_guides/language/spec.md
  src/get-dart/index.md
  src/tools/sdk.md
  src/web/dart-2.md
Labels: review:pm

#5052 Update cover of "Data Structures & Algorithms in Dart" book
  src/assets/img/cover/data-structures-algorithms-dart.png
Labels: RFM

#5035 Add forward link from bottom type discussion to `Never` discussion
  src/null-safety/understanding-null-safety/index.md
Labels: review:tech

#5040 Clean up and fix `dart pub add` page
  src/tools/pub/cmd/pub-add.md
Labels: review:copy

#5059 Cleanup and optimize book listing
  src/_data/books-dart.yml
  src/_data/books-dart2.yml
  src/_data/episodes.yml
  src/assets/img/cover/dart-apprentice-beyond-the-basics.png
  src/assets/img/cover/dart-apprentice-beyond-the-basics.webp
  src/assets/img/cover/dart-apprentice-fundamentals.png
  src/assets/img/cover/dart-apprentice-fundamentals.webp
  src/assets/img/cover/data-structures-algorithms-dart.png
  src/assets/img/cover/data-structures-algorithms-dart.webp
  src/assets/img/cover/o-guia-de-dart.jpeg
  src/assets/img/cover/o-guia-de-dart.webp
  src/assets/img/cover/quick-start-guide.png
  src/resources/books.md
Labels: RFM

#5038 Remove old language tour TODOs now tracked elsewhere
  src/language/built-in-types.md
  src/language/constructors.md
  src/language/generics.md
  src/language/keywords.md
Labels: RFM

#5060 Update site to build with Dart 3.0.6
  Dockerfile
  src/_data/pkg-vers.json
Labels: review:any

#5058 Specify analysis exclusion glob patterns should be relative
  src/tools/analysis.md
Labels: RFM

#5027 Add indicator that narrow TOC can be expanded
  src/_includes/navigation-toc.html
  src/_sass/components/_toc.scss
Labels: review:copy, RFM

#5033 Direct users to bitwise operation platform differences
  examples/misc/test/language_tour/operators_test.dart
  src/language/operators.md
Labels: RFM

#5065 Adjust focus of web difference mention for bitwise operands
  examples/misc/test/language_tour/operators_test.dart
  src/language/operators.md
Labels: RFM

#5066 Add diagnostic glossary entries to main glossary
  src/_data/side-nav.yml
  src/resources/glossary.md
Labels: RFM

#5075 Add 3.0.3 `dart:async` interface changes to migration guide
  src/resources/dart-3-migration.md
Labels: review:copy

#5090 Update github/codeql-action to 2.21.2
  .github/workflows/codeql-analysis.yml
  .github/workflows/scorecards-analysis.yml
Labels: review:any
