Repository dart-lang/site-www, pull requests merged in 2023-03, with the labels that each got.

#4633 Update experiment-flags.md
  src/tools/experiment-flags.md
Labels: RFM

#4647 Reintroduce missing anchors on old language tour
  src/_guides/language/language-tour.md
Labels: review:any

#4645 Rename 'Collection types' to 'Collections'
  firebase.json
  src/_data/side-nav.yml
  src/_guides/language/effective-dart/usage.md
  src/_guides/language/evolution.md
  src/_guides/language/language-tour.md
  src/index.html
  src/language/built-in-types.md
  src/language/collections.md
  src/language/control-flow.md
  src/language/enum.md
  src/language/functions.md
  src/language/variables.md
Labels: blocked

#4643 Priority fixes for 'Breaking up language tour'
  CONTRIBUTING.md
  firebase.json
  src/_data/side-nav.yml
  src/_guides/language/language-tour.md
  src/_includes/navigation-main.html
  src/_includes/navigation-side.html
  src/language/callable-classes.md
  src/language/constructors.md
  src/language/extension-methods.md
  src/language/functions.md
Labels: review:any

#4646 Update redirects to new locations after 'Breaking up language tour'
  firebase.json
Labels: blocked

#4659 Add a clear warning to the top of the old language tour
  src/_guides/language/language-tour.md
Labels: review:copy

#4664 Fix build for latest beta changes
  Dockerfile
  examples/analysis/analyzer-results-beta.txt
Labels: review:any

#4674 Make '/resources' pages highlight 'Docs' and move some pages
  firebase.json
  src/_data/side-nav.yml
  src/_guides/whats-new.md
  src/_includes/navigation-main.html
  src/_includes/navigation-side.html
  src/resources/dart-team-packages.md
  src/resources/faq.md
  src/resources/index.md
  src/tools/dartpad/troubleshoot.md
  src/tools/webdev.md
Labels: review:copy

#4669 Remove the function name firstWhereWithOrElse() from example
  src/codelabs/iterables.md
Labels: cla: yes, review:tech

#4665 Update for latest gem releases
  Gemfile.lock
Labels: RFM

#4689 Fix spelling of Asynchrony
  src/language/async.md
Labels: review:any

#4697 Remove This Week in Dart link for now
  src/community/index.md
Labels: review:any

#4690 Updates for latest linter rules
  src/_data/linter_rules.json
Labels: review:any

#4700 Remove outdated Gitter link
  src/community/index.md
Labels: RFM

#4701 Switch tooling SDK constraints to caret syntax
  examples/analysis/pubspec.yaml
  examples/analysis_alt/pubspec.yaml
  examples/async_await/pubspec.yaml
  examples/build_runner_usage/pubspec.yaml
  examples/concurrency/pubspec.yaml
  examples/create_libraries/pubspec.yaml
  examples/extension_methods/pubspec.yaml
  examples/fetch_data/pubspec.yaml
  examples/futures/pubspec.yaml
  examples/html/pubspec.yaml
  examples/iterables/pubspec.yaml
  examples/misc/pubspec.yaml
  examples/non_promotion/pubspec.yaml
  examples/null_safety_codelab/pubspec.yaml
  examples/util/pubspec.yaml
  examples/vector_victor/pubspec.yaml
  pubspec.yaml
  src/_tutorials/libraries/shared-pkgs.md
  tool/dart_tools/pubspec.yaml
  tool/dartpad_picker/pubspec.yaml
  tool/effective_dart_rules/pubspec.yaml
  tool/get-dart/archive/pubspec.yaml
  tool/get-dart/dart_sdk_archive/pubspec.yaml
  tool/get-dart/sdk_builds.dart/pubspec.yaml
  tool/pubspec.yaml
Labels: RFM

#4705 Minor cleanup and fixes on pubspec page
  src/tools/pub/pubspec.md
Labels: RFM

#4703 Use deps.dev for OpenSSF scorecard result link
  README.md
Labels: RFM

#4715 Fix dev channel build for info changed to warning
  examples/analysis/analyzer-results-dev.txt
Labels: RFM

#4699 Add Dart 3.0 diagnostic messages
  src/tools/diagnostic-messages.md
Labels: RFM

#4648 Fix duplicate 'the' on "Creating packages" page
  src/_guides/libraries/create-library-packages.md
Labels: RFM

#4722 Introduce a new banner calling out I/O
  src/_includes/banner.html
Labels: RFM
