Repository dart-lang/site-www, pull requests merged in 2023-09, with the labels that each got.

#5151 Update to latest Node LTS to fix build
  Dockerfile
Labels: review:any

#5157 Update site to build with Dart 3.1.1
  Dockerfile
  examples/language/lib/control_flow/branches.dart
  examples/language/lib/patterns/switch.dart
  src/_data/pkg-vers.json
  src/language/patterns.md
Labels: review:any

#5158 Update homepage DartPad picker to Dart 3
  src/assets/dash/js/dartpad_picker_main.dart.js
  tool/dartpad_picker/analysis_options.yaml
  tool/dartpad_picker/lib/dartpad_picker.dart
  tool/dartpad_picker/pubspec.yaml
  tool/dartpad_picker/web/dartpad_picker_main.dart
Labels: review:tech

#5160 Update Dart archive tooling to Dart 3 and cleanup analysis
  src/get-dart/archive/assets/download_archive.dart.js
  tool/get-dart/archive/analysis_options.yaml
  tool/get-dart/archive/pubspec.yaml
  tool/get-dart/archive/web/download_archive.dart
  tool/get-dart/dart_sdk_archive/analysis_options.yaml
  tool/get-dart/dart_sdk_archive/lib/src/generator.dart
  tool/get-dart/dart_sdk_archive/lib/src/run_app.dart
  tool/get-dart/dart_sdk_archive/lib/src/util.dart
  tool/get-dart/dart_sdk_archive/lib/src/version_selector.dart
  tool/get-dart/dart_sdk_archive/pubspec.yaml
  tool/get-dart/dart_sdk_archive/test/svn_revisions_test.dart
  tool/get-dart/dart_sdk_archive/tool/grind.dart
  tool/get-dart/dart_sdk_archive/web/main.dart
  tool/get-dart/sdk_builds.dart/analysis_options.yaml
  tool/get-dart/sdk_builds.dart/example/print_latest_versions.dart
  tool/get-dart/sdk_builds.dart/lib/sdk_builds.dart
  tool/get-dart/sdk_builds.dart/lib/src/dart_downloads.dart
  tool/get-dart/sdk_builds.dart/lib/src/version_info.dart
  tool/get-dart/sdk_builds.dart/pubspec.yaml
  tool/get-dart/sdk_builds.dart/test/sdk_builds_test.dart
Labels: review:tech

#5166 Update site for Dart 3.1.2 release
  Dockerfile
  src/_data/pkg-vers.json
Labels: review:any

#5163 Migrate to new node download mechanism
  Dockerfile
  Makefile
  README.md
  tool/fetch-node-ppa-sum.sh
Labels: review:tech

#5169 Account for new `dart:core` annotations and clarify deprecated existence
  src/language/metadata.md
Labels: RFM

#5061 Add breaking changes page
  _config.yml
  src/_data/side-nav.yml
  src/resources/breaking-changes.md
Labels: review:tech

#5183 Remove unnecessary permalink overrides
  src/404.html
  src/_guides/language/index.md
  src/community/index.md
  src/map.html
  src/terms.md
  src/tools/pub/troubleshoot.md
Labels: RFM

#5188 Use fenced code blocks for yaml where possible
  src/tools/pub/versioning.md
Labels: RFM

#5187 Mark a few `gitignore` code blocks more specifically
  src/guides/libraries/private-files.md
Labels: RFM

#5200 Update to latest diagnostic messages and linter rule docs
  src/_data/linter_rules.json
  src/tools/diagnostic-messages.md
Labels: review:any

#5165 Updated version constraint copy
  src/tools/pub/dependencies.md
Labels: review:copy

#5196 Don't use the shared includes for now
  src/_includes/breadcrumbs.html
  src/_includes/navigation-side.html
  src/_includes/page-github-links.html
  src/_includes/shared
  src/_includes/sidenav-level-1.html
  src/_includes/sidenav-level-2.html
  src/_includes/sidenav-level-3.html
  src/_includes/sidenav-level-4.html
  src/_layouts/default.html
Labels: RFM

#5197 Manage images in `/articles` under `/assets`
  src/_articles/archive/converters-and-codecs.md
  src/_articles/archive/images/both-queues.png
  src/_articles/archive/images/scheduling-tasks.png
  src/_articles/archive/images/test-annotated.png
  src/_articles/archive/images/test-queue-output.png
  src/_articles/archive/numeric-computation.md
  src/_articles/archive/zones.md
  src/assets/img/articles/converters-and-codecs/chunked-conversion.png
  src/assets/img/articles/numeric-computation/1.png
  src/assets/img/articles/numeric-computation/10.png
  src/assets/img/articles/numeric-computation/11.png
  src/assets/img/articles/numeric-computation/12.png
  src/assets/img/articles/numeric-computation/2.png
  src/assets/img/articles/numeric-computation/3.png
  src/assets/img/articles/numeric-computation/4.png
  src/assets/img/articles/numeric-computation/5.png
  src/assets/img/articles/numeric-computation/6.png
  src/assets/img/articles/numeric-computation/7.png
  src/assets/img/articles/numeric-computation/8.png
  src/assets/img/articles/numeric-computation/9.png
  src/assets/img/articles/zones/trace.png
Labels: RFM

#5191 Move `/null-safety` images to be managed within `/assets`
  src/assets/img/null-safety/migration-tool-incremental.png
  src/assets/img/null-safety/migration-tool.png
  src/assets/img/null-safety/null-safety-migration-order.png
  src/assets/img/null-safety/pub-outdated-output.png
  src/assets/img/null-safety/understanding-null-safety/bifurcate.png
  src/assets/img/null-safety/understanding-null-safety/hierarchy-after.png
  src/assets/img/null-safety/understanding-null-safety/hierarchy-before.png
  src/assets/img/null-safety/understanding-null-safety/nullable-hierarchy.png
  src/assets/img/null-safety/understanding-null-safety/top-and-bottom.png
  src/null-safety/dartpad-snippet.png
  src/null-safety/migration-guide.md
  src/null-safety/understanding-null-safety.md
  src/null-safety/unsound-null-safety.md
Labels: RFM

#5174 Missing quotes in Update patterns.md
  src/language/patterns.md
Labels: review:tech

#5154 refactor(Null safety): fix typo about number of core design principles
  src/null-safety/index.md
Labels: cla: yes

#5216 Update Twitter logo and references to X
  src/_includes/page-footer.html
  src/assets/img/social/twitter.svg
  src/assets/img/social/x.svg
  src/community/index.md
Labels: RFM
