Repository dart-lang/site-www, pull requests merged in 2023-11, with the labels that each got.

#5017 Update Effective Dart on mixins for Dart 3 changes
  examples/misc/lib/effective_dart/design_good.dart
  src/effective-dart/design.md
Labels: st.WIP, review.tech

#5283 Update constructors page
  examples/misc/lib/language_tour/classes/point.dart
  examples/misc/lib/language_tour/classes/point_alt.dart
  src/language/constructors.md
Labels: st.RFM.%

#5318 Update text colors and highlighting for increased contrast
  src/_sass/_overwrites.scss
  src/_sass/components/_code.scss
  src/_sass/components/_sidebar.scss
  src/_sass/components/_toc.scss
  src/_sass/core/_base.scss
  src/_sass/core/_variables.scss
  src/_sass/site.scss
Labels: st.RFM

#5317 Fix and remove duplicated `toc` ID
  src/_includes/navigation-toc.html
  src/_sass/_overwrites.scss
Labels: st.RFM

#5319 Avoid duplicated search box IDs
  src/404.html
  src/_includes/navigation-main.html
  src/_includes/navigation-side.html
Labels: st.RFM

#5327 Update firebase-tools to 12.8.1 for latest fixes
  .github/workflows/build.yml
  Dockerfile
Labels: st.RFM

#5331 [3.2] Update breaking changes page
  src/resources/breaking-changes.md
Labels: st.RFM

#5343 [3.2] `dart create cli`
  src/tools/dart-create.md
Labels: st.RFM

#5330 [3.2] Language evolution
  src/guides/language/evolution.md
Labels: st.RFM

#5353 [3.2] Banner
  src/_includes/banner.html
  src/guides/language/evolution.md
Labels: st.RFM

#5340 [3.2] What's new
  src/guides/whats-new.md
Labels: st.RFM

#5366 Move interop section out from development section
  firebase.json
  src/_data/side-nav.yml
  src/guides/language/evolution.md
  src/guides/libraries/index.md
  src/guides/libraries/library-tour.md
  src/guides/whats-new.md
  src/interop/c-interop.md
  src/interop/java-interop.md
  src/interop/js-interop.md
  src/interop/objective-c-interop.md
  src/resources/faq.md
  src/tools/diagnostic-messages.md
  src/web/index.md
  src/web/libraries.md
Labels: st.RFM

#5374 Update `be` SDK build links to use `main` instead
  src/get-dart/archive/index.md
Labels: review.tech

#5379 Update diagnostic messages for extension types and other fixes
  src/tools/diagnostic-messages.md
Labels: review.copy

#5380 Update site for Dart 3.2.2 release
  Dockerfile
  src/_data/pkg-vers.json
Labels: st.RFM
