Repository dart-lang/site-www, pull requests merged in 2023-10, with the labels that each got.

#5225 Update site for release of Dart 3.1.3
  src/_data/pkg-vers.json
Labels: review:tech

#5231 Update for latest diagnostic messages
  src/_data/linter_rules.json
  src/tools/diagnostic-messages.md
Labels: RFM

#5228 Update package-layout.md to include the integration_test dir
  src/tools/pub/package-layout.md
Labels: review:tech

#5241 Remove old cheatsheet
  firebase.json
  src/codelabs/dart-cheatsheet.md
  src/guides/language/cheatsheet.md
Labels: RFM

#5239 Remove ephemeral `Dockerfile.save` file
  Dockerfile.save
Labels: review:any

#5240 Reduce padding at top of content
  src/_sass/core/_variables.scss
Labels: RFM

#5248 Fix a few spelling mistakes in dart compile docs
  src/overview.md
  src/resources/faq.md
  src/tools/dart-compile.md
Labels: RFM

#5260 Updates dependabot and no-response pages with new GitHub labels
  .github/dependabot.yml
  .github/workflows/no-response.yaml
Labels: st.RFM

#5261 Minor language update.
  src/effective-dart/design.md
Labels: st.RFM

#5258 Update guard clause content
  examples/language/lib/control_flow/branches.dart
  src/language/branches.md
  src/language/patterns.md
Labels: st.RFM

#5263 Exclude internal linter rules from generated docs
  src/_includes/linter-rules-section.md
  src/_plugins/linter_page_generator.rb
  src/tools/linter-rules/all.md
Labels: review.tech

#5266 Update linter docs for lints 3.0 release
  src/_data/linter_rules.json
  src/_includes/linter-page-content.md
  src/tools/diagnostic-messages.md
Labels: review.copy

#5276 Fixes to the command line tutorial
  src/tutorials/server/cmdline.md
Labels: review.copy

#5272 Reduce home page load time by lazy loading DartPad iframe
  src/assets/dash/js/dartpad_picker_main.dart.js
  src/index.html
  tool/dartpad_picker/lib/dartpad_picker.dart
  tool/dartpad_picker/pubspec.yaml
Labels: st.RFM

#5287 Update site for release of Dart 3.1.5
  Dockerfile
  src/_data/pkg-vers.json
Labels: review.tech

#5282 Don't run tests on the dev channel for now to fix build
  .github/workflows/build.yml
Labels: review.tech
