Repository dart-lang/site-www, pull requests merged in 2024-05, with the labels that each got.

#5760 Update default pnpm and dependencies
  package.json
  pnpm-lock.yaml
Labels: review.tech

#5765 Add I/O register now banner
  src/_includes/banner.html
Labels: review.copy

#5771 Consolidate async docs away from old directories
  firebase.json
  src/_data/side-nav.yml
  src/content/articles/archive/zones.md
  src/content/guides/language/coming-from/swift-to-dart.md
  src/content/libraries/async/creating-streams.md
  src/content/libraries/async/futures-error-handling.md
  src/content/libraries/async/using-streams.md
  src/content/libraries/dart-async.md
  src/content/tutorials/index.md
  src/content/tutorials/language/index.md
Labels: st.RFM

#5757 Refactor Constructors page
  examples/misc/lib/language_tour/classes/point_alt.dart
  examples/misc/lib/language_tour/classes/super_initializer_named_parameters.dart
  examples/misc/lib/language_tour/classes/super_initializer_positional_parameters.dart
  src/content/guides/whats-new.md
  src/content/language/classes.md
  src/content/language/constructors.md
Labels: st.RFM

#5780 Add temp go link for json_codable
  firebase.json
Labels: review.await-update

#5801 [3.4] Update breaking changes page
  src/content/resources/breaking-changes.md
Labels: review.copy

#5800 Update lints constraints to v4
  examples/analysis/pubspec.yaml
  examples/analysis_alt/pubspec.yaml
  examples/async_await/pubspec.yaml
  examples/build_runner_usage/pubspec.yaml
  examples/cli/pubspec.yaml
  examples/concurrency/pubspec.yaml
  examples/create_libraries/pubspec.yaml
  examples/extension_methods/pubspec.yaml
  examples/fetch_data/pubspec.yaml
  examples/futures/pubspec.yaml
  examples/html/pubspec.yaml
  examples/iterables/pubspec.yaml
  examples/language/pubspec.yaml
  examples/misc/pubspec.yaml
  examples/non_promotion/pubspec.yaml
  examples/null_safety_codelab/pubspec.yaml
  examples/type_system/pubspec.yaml
  examples/util/pubspec.yaml
  examples/vector_victor/pubspec.yaml
  pubspec.yaml
  src/content/tutorials/server/cmdline.md
Labels: review.tech

#5781 Wasm landing page
  src/_data/side-nav.yml
  src/content/interop/js-interop/index.md
  src/content/interop/js-interop/js-types.md
  src/content/interop/js-interop/package-web.md
  src/content/interop/js-interop/past-js-interop.md
  src/content/overview.md
  src/content/tools/dart-compile.md
  src/content/web/wasm.md
Labels: review.pm

#5815 Remedies GAR 1.6 violations
  src/content/guides/index.md
  src/content/guides/language/index.md
  src/content/resources/index.md
Labels: review.copy

#5830 Fix super reference
  examples/misc/lib/language_tour/classes/employee.dart
  src/content/language/constructors.md
Labels: review.tech

#5808 Better prerelease docs
  src/content/tools/pub/publishing.md
Labels: st.RFM

#5803 Update pub-lish.md
  src/content/tools/pub/cmd/pub-lish.md
Labels: st.RFM

#5842 Update linter rules for latest 3.5 dev changes
  src/_data/linter_rules.json
Labels: review.copy

#5853 Hide unreleased lints in all list
  src/content/tools/linter-rules/all.md
Labels: review.tech

#5852 Update for latest FFI diagnostic updates
  src/content/tools/diagnostic-messages.md
Labels: review.copy

#5850 Added constructor tear-offs
  examples/misc/lib/language_tour/tear_offs.dart
  examples/misc/test/language_tour/functions_test.dart
  src/content/effective-dart/usage.md
  src/content/language/constructors.md
  src/content/language/functions.md
Labels: st.RFM

#5848 Added Art of Dart
  src/_data/books-dart.yml
  src/content/assets/img/cover/art-of-dart.webp
Labels: review.copy

#5845 Refactor dart format
  src/content/tools/dart-format.md
Labels: review.copy

#5854 Updated note on arrow notation
  src/content/language/functions.md
Labels: review.tech

#5883 Update diagnostic docs and fix a few linter docs
  src/_data/linter_rules.json
  src/content/tools/diagnostic-messages.md
Labels: review.copy

#5864 Changed all sdk refs to use caret syntax
  src/content/tools/pub/dependencies.md
  src/content/tools/pub/pubspec.md
Labels: review.copy

#5694 "Specify members" and "access state" for mixins
  src/content/language/mixins.md
Labels: review.copy

#5881 Refactor C interop
  src/content/guides/whats-new.md
  src/content/interop/c-interop.md
Labels: review.copy

#5884 Support specifying attributes to DartPad
  src/_11ty/plugins/highlight.js
  src/content/codelabs/async-await.md
  src/content/codelabs/dart-cheatsheet.md
  src/content/codelabs/iterables.md
  src/content/language/callable-objects.md
  src/content/language/constructors.md
  src/content/language/functions.md
  src/content/libraries/async/using-streams.md
  src/content/overview.md
  src/content/tutorials/server/fetch-data.md
  src/content/tutorials/server/get-started.md
Labels: st.RFM.%

#5882 Update node, pnpm, and npm dependencies
  README.md
  dash_site
  package.json
  pnpm-lock.yaml
  src/_data/site.yml
Labels: review.tech

#5838 Best practices for downgrade testing
  src/content/tools/pub/dependencies.md
Labels: st.RFM.%

#5865 Add info on filename versions
  src/content/tools/pub/versioning.md
Labels: st.RFM.%

#5826 Adds uninstall
  src/_includes/install/linux.md
  src/_includes/install/macos.md
  src/_includes/install/windows.md
  src/content/get-dart/_linux.md
  src/content/get-dart/index.md
Labels: st.RFM.%
