Repository dart-lang/site-www, pull requests merged in 2024-02, with the labels that each got.

#5500 Update isolates.md - TODOs are reversed
  examples/concurrency/lib/basic_ports_example/start.dart
  src/language/isolates.md
Labels: st.RFM.%

#5479 Revise Dart FAQ
  _config.yml
  src/_data/side-nav.yml
  src/_sass/site.scss
  src/guides/whats-new.md
  src/resources/faq.md
  src/resources/index.md
  src/tools/dartpad/troubleshoot.md
  src/tools/webdev.md
Labels: review.tech

#5514 Add Dart PT-BR Course
  src/_includes/yt_shims.liquid
  src/resources/videos.md
Labels: review.copy

#5504 Document ignoring diagnostics in pubspec files
  src/content/tools/analysis.md
Labels: review.copy

#5518 Standardize icons on Material Symbols
  src/_11ty/plugins/markdown.js
  src/_includes/head.html
  src/_includes/navigation-main.html
  src/_includes/navigation-toc-top.html
  src/_includes/page-github-links.html
  src/_sass/_site.scss
  src/_sass/components/_header.scss
  src/_sass/components/_sidebar.scss
  src/_sass/core/_variables.scss
  src/content/index.html
  src/content/resources/faq.md
  src/content/tools/dart-devtools.md
  src/content/web/get-started.md
Labels: review.tech

#5511 Add HTTP libraries
  src/_data/site.yml
  src/content/guides/libraries/useful-libraries.md
  src/content/tutorials/server/fetch-data.md
  src/content/tutorials/server/httpserver.md
Labels: review.tech

#5531 Update set up instructions and pnpm dependencies
  README.md
  package.json
  pnpm-lock.yaml
Labels: st.RFM

#5497 Updated supported platform language
  src/_data/macos.json
  src/_sass/_site.scss
  src/content/get-dart/_linux.md
  src/content/get-dart/_mac.md
  src/content/get-dart/_windows.md
  src/content/get-dart/archive/_sdk-terms.md
  src/content/get-dart/index.md
Labels: review.tech

#5546 Misc cleanup to class modifier page
  examples/language/lib/class_modifiers/ex1/a.dart
  examples/language/lib/class_modifiers/ex1/b.dart
  examples/language/lib/class_modifiers/ex2/a.dart
  examples/language/lib/class_modifiers/ex2/b.dart
  examples/language/lib/class_modifiers/ex3/a.dart
  examples/language/lib/class_modifiers/ex3/b.dart
  examples/language/lib/class_modifiers/ex4/a.dart
  examples/language/lib/class_modifiers/ex4/b.dart
  examples/language/lib/class_modifiers/ex5/sealed.dart
  examples/language/lib/class_modifiers/sealed_exhaustiveness.dart
  examples/misc/test/language_tour/functions_test.dart
  src/content/language/class-modifiers.md
  src/content/language/functions.md
Labels: review.copy

#5569 Clarify how class modifiers aren't accepted by extension types
  src/content/language/class-modifiers.md
  src/content/language/modifier-reference.md
Labels: review.copy

#5568 Implement code block copy button
  src/_sass/components/_code.scss
  src/content/assets/js/main.js
Labels: st.RFM

#5557 Extension types follow up
  src/content/language/extension-types.md
Labels: review.tech

#5588 Fix a few issues on the "Get the Dart SDK" page
  src/_sass/_site.scss
  src/content/get-dart/index.md
Labels: review.copy

#5567 Consolidate and simplify styles
  src/_data/side-nav.yml
  src/_includes/navigation-main.html
  src/_includes/navigation-side.html
  src/_includes/navigation-toc-side.html
  src/_includes/navigation-toc-top.html
  src/_includes/sidenav-level-1.html
  src/_includes/sidenav-level-2.html
  src/_includes/sidenav-level-3.html
  src/_includes/sidenav-level-4.html
  src/_sass/_os-tabs.scss
  src/_sass/_site.scss
  src/_sass/components/_header.scss
  src/_sass/components/_sidebar.scss
  src/_sass/components/_toc.scss
  src/_sass/core/_variables.scss
Labels: review.tech

#5595 Fix heading levels on libraries pages
  src/_11ty/filters.js
  src/_11ty/plugins/highlight.js
  src/content/articles/archive/converters-and-codecs.md
  src/content/articles/archive/zones.md
  src/content/libraries/dart-async.md
  src/content/libraries/dart-convert.md
  src/content/libraries/dart-core.md
  src/content/libraries/dart-html.md
  src/content/libraries/dart-io.md
  src/content/libraries/dart-math.md
Labels: review.copy

#5606 Add a shell script to validate setup and defer to tooling
  README.md
  dash_site
  package.json
Labels: review.tech
