Repository dart-lang/site-www, pull requests merged in 2024-04, with the labels that each got.

#5681 Update keyword list
  src/_data/keywords.yml
  src/_sass/_site.scss
  src/content/language/keywords.md
  src/content/tools/index.md
  src/content/tools/pub/custom-package-repositories.md
Labels: review.tech

#5679 Suggest null-check patterns for type promo
  examples/misc/lib/effective_dart/usage_good.dart
  src/content/effective-dart/_toc.md
  src/content/effective-dart/usage.md
  src/content/guides/whats-new.md
Labels: review.await-update

#5702 Update keyword list per Erik's feedback
  src/_data/keywords.yml
  src/content/language/keywords.md
Labels: review.tech

#5698 Update built-in-types.md
  examples/misc/test/language_tour/built_in_types_test.dart
  src/content/language/built-in-types.md
Labels: review.tech

#5706 Add replacement suggestion
  src/content/tools/pub/publishing.md
Labels: review.tech

#5707 Fix 404 page missing from site
  src/content/404.html
Labels: review.tech

#5720 Update and prune pnpm dependencies
  package.json
  pnpm-lock.yaml
Labels: st.RFM

#5719 Updated methods/operators section
  src/content/language/methods.md
Labels: review.tech

#5717 Edit dart pub token page
  src/content/tools/pub/cmd/pub-token.md
Labels: review.copy
