Repository dart-lang/site-www, pull requests merged in 2024-06, with the labels that each got.

#5876 Clarify capitalization of abbr and acronym
  src/content/effective-dart/style.md
Labels: review.tech

#5869 Added new dart book
  src/_data/books-dart.yml
  src/content/assets/img/cover/basics-dart.webp
Labels: cla: yes, review.await-update

#5889 Fix factory constructor example
  src/content/codelabs/dart-cheatsheet.md
Labels: st.RFM

#4958 Glossary entries for "Subtype" and "Subclass"
  src/content/resources/glossary.md
Labels: review.copy

#5894 Adds skip to main link
  src/_layouts/default.html
  src/_sass/_site.scss
Labels: review.tech

#5906 Fix brand link
  src/content/brand.md
Labels: review.copy

#5919 Add pub.dev filter to wasm page
  src/content/web/wasm.md
Labels: st.RFM.%

#5923 Fix incorrect optimization of gifs
  eleventy.config.js
Labels: st.RFM

#5924 Add styled tags to breaking changes page
  src/_sass/_site.scss
  src/_sass/components/_tags.scss
  src/content/resources/breaking-changes.md
Labels: review.copy, review.tech

#5937 Add redirect for tooling to the main function docs
  firebase.json
  src/content/language/functions.md
Labels: st.RFM

#5941 Update pattern-types.md
  src/content/language/pattern-types.md
Labels: st.RFM

#5945 Update GitHub links on SDK page
  src/content/tools/sdk.md
Labels: review.copy

#5939 Add note informing users not to install Flutter and Dart separately
  src/content/get-dart/index.md
Labels: st.RFM

#5949 Changed skip to physical button
  src/_sass/_site.scss
  src/_sass/core/_variables.scss
Labels: review.tech
