Repository dart-lang/site-www, pull requests merged in 2024-03, with the labels that each got.

#5620 Correct type explanation on Extension types page
  src/content/language/extension-types.md
Labels: review.copy, review.tech

#5621 Revise "Web libraries and packages" page
  src/content/web/libraries.md
Labels: st.RFM

#5628 Replace custom mini-toc container with secondary
  src/_11ty/plugins/markdown.js
  src/_sass/_site.scss
  src/content/tutorials/language/streams.md
  src/content/tutorials/server/cmdline.md
  src/content/tutorials/server/fetch-data.md
Labels: review.tech

#5637 Fix missing space on 'Class modifiers' page
  src/content/language/class-modifiers.md
Labels: cla: yes

#5638 Update 54801 issue note
  src/content/interop/js-interop/usage.md
Labels: review.copy

#5648 Fix formatting of operator table on Methods page
  src/content/language/methods.md
Labels: review.copy

#5607 Mark IA32 support as deprecated in system requirements table
  src/_sass/_site.scss
  src/content/get-dart/index.md
Labels: review.pm

#5657 Clarified parenthetical patterns
  examples/language/lib/patterns/pattern_types.dart
  src/content/language/pattern-types.md
Labels: review.tech

#5489 Updated deferred language
  src/content/language/libraries.md
  src/content/resources/breaking-changes.md
Labels: st.RFM

#5664 Update diagnostic messages and linter rules
  src/_data/linter_rules.json
  src/_data/side-nav.yml
  src/_data/site.yml
  src/content/tools/diagnostic-messages.md
Labels: review.copy

#5431 Added info on dependency version constraints
  src/content/tools/pub/dependencies.md
Labels: st.RFM.%

#5667 Fix and standardize various links in JS interop docs
  src/content/interop/js-interop/index.md
  src/content/interop/js-interop/js-types.md
  src/content/interop/js-interop/mock.md
  src/content/interop/js-interop/package-web.md
  src/content/interop/js-interop/past-js-interop.md
  src/content/interop/js-interop/usage.md
Labels: review.copy
